# -*- coding: utf-8 -*-
# 20 neue medium-Cases im Casebook-Format.
# Format: {difficulty, category, prompt, framework, qa, tree, notes}

NEW_MEDIUM = [

{"category": "profitability", "framework": "Profitability Framework",
 "prompt": "Dein Klient ist BackWerk24, eine Bäckereikette mit 60 Filialen und eigener Großbäckerei. Trotz gestiegener Preise sinkt der Gewinn seit zwei Jahren. Der Inhaber bittet dich um eine strukturierte Ursachenanalyse mit Empfehlungen.",
 "qa": [
  ("Was ist das Ziel?", "Zurück zur alten Umsatzrendite innerhalb von 18 Monaten — ohne die Marke zu beschädigen."),
  ("Sind die Preiserhöhungen angekommen?", "Ja, aber sie haben die Kostensteigerungen nur teilweise aufgefangen; die Stückzahlen gingen leicht zurück."),
  ("Welche Kosten sind gestiegen?", "Energie für die Großbäckerei und Öfen, Rohstoffe (Mehl, Butter) und Personal — Energie am stärksten."),
  ("Wie viel wird weggeworfen?", "Die Retourenquote (unverkaufte Ware) liegt deutlich über Branchenschnitt — abends sind die Theken bewusst voll."),
  ("Unterscheiden sich die Filialen?", "Ja, stark: Bahnhofslagen laufen gut, einige Wohngebietsfilialen kaum kostendeckend."),
 ],
 "tree": [
  {"t": "Kostenseite", "star": True, "b": ["Energie: Effizienz Großbäckerei & Öfen", "Rohstoffe: Einkauf, Rezepturen"], "c": [{"t": "Personaleinsatz nach Frequenz steuern", "b": []}]},
  {"t": "Umsatz & Sortiment", "b": ["Preis-/Mengeneffekt je Produktgruppe", "Snack-/Kaffeegeschäft mit höherer Marge pushen"]},
  {"t": "Verschwendung & Retouren", "b": ["Bedarfsprognose je Filiale & Tageszeit", "Abverkaufslogik am Abend (Rabatte, Apps)"]},
  {"t": "Filialportfolio", "b": ["Filial-P&L: Lagen clustern", "Schwache Standorte sanieren oder schließen"]},
 ],
 "notes": "Mehrschichtiges Kostenproblem: Energie + Retouren sind die stillen Margenkiller. Starke Antworten quantifizieren den Preis-Mengen-Effekt und differenzieren nach Filialen statt pauschal zu sparen."},

{"category": "profitability", "framework": "Profitability Framework",
 "prompt": "Dein Klient ist ein ambulanter Pflegedienst mit 120 Mitarbeitenden. Die Nachfrage ist hoch, die Touren sind voll — trotzdem ist das Ergebnis kaum positiv. Die Geschäftsführerin fragt: Woran liegt das, und welche Hebel haben wir?",
 "qa": [
  ("Wie werden Leistungen vergütet?", "Über feste Pflegekassen-Sätze je Leistung — die Preise sind also weitgehend vorgegeben, verhandelt wird selten."),
  ("Wo geht Zeit verloren?", "Lange Fahrzeiten zwischen Klienten und viel unbezahlte Dokumentationszeit — die Tourenplanung erfolgt manuell."),
  ("Wie ist der Leistungsmix?", "Viele kurze, schlecht vergütete Einsätze; besser vergütete Behandlungspflege macht nur einen kleinen Teil aus."),
  ("Wie hoch sind Ausfälle und Fluktuation?", "Beides über Branchenschnitt — Springer und Überstunden verteuern jede Woche."),
  ("Gibt es Spielraum bei den Kassen?", "Vergütungsverhandlungen sind möglich, wurden aber seit Jahren nicht geführt."),
 ],
 "tree": [
  {"t": "Produktivität der Touren", "star": True, "b": ["Tourenoptimierung (Software, Gebiete)", "Dokumentation digitalisieren (Zeit je Einsatz)"], "c": [{"t": "Einsatzarten bündeln: weniger Leerfahrten", "b": []}]},
  {"t": "Leistungs- & Klientenmix", "b": ["Behandlungspflege & besser vergütete Leistungen ausbauen", "Unwirtschaftliche Einsätze neu verhandeln oder abgeben"]},
  {"t": "Vergütung", "b": ["Kassenverhandlungen vorbereiten (Kostennachweis)", "Privatleistungen ergänzen"]},
  {"t": "Personalstabilität", "b": ["Fluktuation senken (Dienstplanqualität)", "Ausfallmanagement statt teurer Springer"]},
 ],
 "notes": "Bei regulierten Preisen liegt der Hebel in Produktivität (Fahr-/Doku-Zeit) und Leistungsmix. Wer nur 'Preise erhöhen' sagt, hat das Vergütungssystem nicht verstanden."},

{"category": "profitability", "framework": "Profitability Framework",
 "prompt": "Dein Klient betreibt drei Indoor-Spielplätze für Familien. Zwei laufen profitabel, der dritte — der größte und neueste — verliert Geld. Der Geschäftsführer will wissen, ob er ihn retten kann.",
 "qa": [
  ("Was unterscheidet den dritten Standort?", "Er ist doppelt so groß, liegt am Stadtrand im Gewerbegebiet und hat die höchste Miete."),
  ("Wie sind die Besucherzahlen?", "Am Wochenende ordentlich, unter der Woche fast leer — deutlich schlechter als die beiden anderen."),
  ("Wie setzt sich der Umsatz zusammen?", "Eintritt plus Gastronomie; Geburtstagsfeiern sind das margenstärkste Produkt, dort ist er aber schwach gebucht."),
  ("Wie lange läuft der Mietvertrag?", "Noch sieben Jahre, mit Option auf Untervermietung von Teilflächen."),
  ("Was kostet der Betrieb unter der Woche?", "Fast so viel wie am Wochenende — Personal- und Energiekosten laufen weitgehend durch."),
 ],
 "tree": [
  {"t": "Diagnose: Warum defizitär?", "b": ["Standort-P&L vs. die zwei profitablen", "Frequenz-, Preis- oder Kostenproblem?"]},
  {"t": "Auslastung Wochentage", "star": True, "b": ["Kitas/Schulen, Kurse, Vereins-Kooperationen", "Off-Peak-Preise & Abos für Vielbesucher"], "c": [{"t": "Geburtstags-/Eventgeschäft aktiv vermarkten", "b": []}]},
  {"t": "Kosten & Fläche", "b": ["Öffnungszeiten & Personaleinsatz flexibilisieren", "Teilfläche untervermieten (Option nutzen)"]},
  {"t": "Exit-Vergleich", "b": ["Turnaround-Case vs. Schließungskosten (7 Jahre Miete)", "Entscheidung mit Meilensteinen"]},
 ],
 "notes": "Fixkosten-lastiges Freizeitgeschäft: Der Hebel ist Wochentags-Auslastung + Eventgeschäft; die Untervermietungs-Option ist das Sicherheitsnetz. Ein Entscheidungsrahmen (retten vs. exit) gehört dazu."},

{"category": "profitability", "framework": "Profitability / Portfolio Framework",
 "prompt": "Dein Klient ist eine Werbeagentur mit 80 Mitarbeitenden. Der Umsatz wächst, aber die Marge schrumpft seit drei Jahren. Die Gründer ahnen, dass einige Kunden und Projekte Geld verbrennen — Transparenz fehlt. Strukturiere die Analyse.",
 "qa": [
  ("Gibt es eine Projekt-Nachkalkulation?", "Nein — Stunden werden erfasst, aber nie gegen die Angebote ausgewertet."),
  ("Wie wird verkauft?", "Überwiegend Festpreise, kalkuliert vom jeweiligen Beratungsteam — Rabatte bei Pitches sind üblich."),
  ("Welche Kunden wachsen?", "Zwei Großkunden mit vielen kleinen Change-Requests, die selten berechnet werden."),
  ("Wie ist die Auslastung?", "Kreation ist überbucht, Strategie unterausgelastet — Freelancer füllen teuer die Spitzen."),
  ("Was ist das Ziel der Gründer?", "Marge zurück auf Branchenniveau, ohne Kernkunden zu verlieren."),
 ],
 "tree": [
  {"t": "Transparenz schaffen", "star": True, "b": ["Nachkalkulation je Projekt & Kunde", "Profitabilitäts-Ranking: Wer verbrennt Geld?"], "c": [{"t": "Ursachen: Scope Creep, Rabatte, Fehlkalkulation", "b": []}]},
  {"t": "Kommerzielle Disziplin", "b": ["Change-Requests konsequent bepreisen", "Rabatt-Governance bei Pitches"]},
  {"t": "Ressourcen & Auslastung", "b": ["Kapazitätsplanung Kreation vs. Strategie", "Freelancer-Einsatz steuern"]},
  {"t": "Portfolio-Entscheidungen", "b": ["Unprofitable Kunden sanieren oder trennen", "Wachstum auf margenstarke Leistungen lenken"]},
 ],
 "notes": "Professional-Services-Klassiker: Ohne Projekt-P&L keine Steuerung. Scope Creep bei Großkunden ist der versteckte Margenkiller — wer Transparenz → Disziplin → Portfolio logisch aufbaut, punktet."},

{"category": "market_entry", "framework": "Market Entry Framework",
 "prompt": "Dein Klient ist ein erfolgreicher Berliner Anbieter von Kochboxen-Abos. Er überlegt, in den österreichischen und Schweizer Markt zu expandieren. Wie würdest du die Entscheidung strukturieren?",
 "qa": [
  ("Was ist das Ziel der Expansion?", "Neues Wachstum, weil der deutsche Markt zunehmend gesättigt ist — profitabel innerhalb von zwei Jahren je Markt."),
  ("Wie unterscheiden sich die Märkte?", "Österreich ähnelt Deutschland; die Schweiz hat höhere Zahlungsbereitschaft, aber auch deutlich höhere Logistik- und Zutatenkosten plus Zollgrenze."),
  ("Gibt es dort schon Wettbewerber?", "Ein internationaler Player ist in beiden Ländern aktiv, lokale Anbieter sind klein."),
  ("Kann die bestehende Logistik genutzt werden?", "Für Österreich teilweise (Lieferung aus Bayern denkbar); die Schweiz bräuchte wegen Zoll und Frische ein eigenes Setup."),
  ("Wie stark ist die Marke dort?", "Kaum bekannt — Marketing müsste von vorn aufgebaut werden."),
 ],
 "tree": [
  {"t": "Marktattraktivität je Land", "b": ["Marktgröße, Abo-Affinität, Zahlungsbereitschaft", "Wettbewerbsintensität AT vs. CH"]},
  {"t": "Operative Machbarkeit", "star": True, "b": ["AT: Belieferung aus DE-Netz möglich", "CH: Zoll, eigenes Lager, Zutaten-Sourcing"], "c": [{"t": "Frische-/Lieferzeit-Anforderungen je Land", "b": []}]},
  {"t": "Go-to-Market", "b": ["Lokalisierung: Rezepte, Preise, Marketing", "CAC-Annahmen & Startregionen"]},
  {"t": "Business Case & Sequenz", "b": ["Investment & Break-even je Land", "Empfehlung: AT zuerst, CH nach Beweis"]},
 ],
 "notes": "Zweiländer-Vergleich mit operativer Pointe: Österreich ist der logistisch einfache Einstieg, die Schweiz der margenreiche, aber teure Sonderfall. Eine Sequenz-Empfehlung wird erwartet."},

{"category": "market_entry", "framework": "Market Entry Framework",
 "prompt": "Dein Klient stellt hochwertige E-Bikes her und verkauft bisher nur über Fachhändler. Jetzt überlegt er, einen eigenen Online-Direktvertrieb zu starten. Strukturiere die Entscheidung.",
 "qa": [
  ("Warum will der Klient D2C?", "Höhere Marge, direkter Kundenzugang und Unabhängigkeit — Online-Pure-Player wachsen schneller als der Fachhandel."),
  ("Wie wichtig ist der Fachhandel heute?", "Er macht praktisch den gesamten Absatz und übernimmt Beratung, Probefahrten und Service."),
  ("Wie reagieren Händler auf D2C-Pläne?", "Sehr empfindlich — ein großer Händlerverbund hat bereits mit Auslistung gedroht."),
  ("Wer übernimmt Service und Garantie online?", "Ungeklärt — E-Bikes brauchen Montage, Inspektionen und Reparaturnetz."),
  ("Was machen Wettbewerber?", "Zwei Premium-Marken fahren hybride Modelle mit Online-Kauf und Händler-Übergabe."),
 ],
 "tree": [
  {"t": "Kanalkonflikt", "star": True, "b": ["Händler-Reaktionen & Abhängigkeit quantifizieren", "Hybrid-Modelle: Online-Kauf, Händler-Übergabe"], "c": [{"t": "Händler einbinden: Provision auf D2C-Umsätze", "b": []}]},
  {"t": "Kundennutzen & Nachfrage", "b": ["Wer kauft online? (Segment, Preislage)", "Beratung/Probefahrt digital ersetzen?"]},
  {"t": "Operative Voraussetzungen", "b": ["Versand, Montagegrad, Retouren", "Servicenetz für Online-Kunden"]},
  {"t": "Wirtschaftlichkeit", "b": ["Margen-Vergleich D2C vs. Handel (voll kalkuliert)", "Pilot mit Modell-Teilsortiment"]},
 ],
 "notes": "Kein reiner Online-Case, sondern Kanalkonflikt-Management: Das Hybrid-Modell mit Händlereinbindung ist die reife Antwort. Service/Montage entscheidet über D2C-Tauglichkeit."},

{"category": "market_entry", "framework": "Market Entry Framework",
 "prompt": "Dein Klient ist eine regionale Brauerei mit starker Marke. Der Biermarkt schrumpft, und die Geschäftsführung will in den wachsenden Markt für alkoholfreie Erfrischungsgetränke (Limonaden, Schorlen) einsteigen. Wie gehst du vor?",
 "qa": [
  ("Was ist das Ziel?", "Ein zweites Standbein, das in fünf Jahren einen relevanten Umsatzanteil liefert."),
  ("Welche Stärken bringt die Brauerei mit?", "Bekannte Regionalmarke, eigene Abfüllung, Logistik und beste Beziehungen zu Gastronomie und Handel der Region."),
  ("Wie sieht der Limonadenmarkt aus?", "Wächst, besonders bei natürlichen/zuckerreduzierten Produkten — besetzt von Konzernen und trendigen Startups."),
  ("Kann die Anlage Limonade abfüllen?", "Ja, mit überschaubarer Umrüstung — freie Kapazitäten sind vorhanden."),
  ("Gibt es schon Produktideen?", "Ein Braumeister-Team hat Prototypen mit regionalen Zutaten entwickelt, aber nichts ist getestet."),
 ],
 "tree": [
  {"t": "Markt & Positionierung", "b": ["Segment: natürlich/regional statt Mainstream", "Wettbewerb: Konzerne vs. Trend-Startups"]},
  {"t": "Eigene Stärken nutzen", "star": True, "b": ["Marke regional dehnen — passt sie zu Limo?", "Abfüllung, Logistik, Gastro-/Handelszugang"], "c": [{"t": "Gastronomie als Launch-Kanal", "b": []}]},
  {"t": "Produkt & Test", "b": ["Prototypen im Markt testen (Gastro-Pilot)", "Preispositionierung Premium-Regional"]},
  {"t": "Wirtschaftlichkeit & Risiken", "b": ["Umrüstkosten & Deckungsbeitrag je Kiste", "Markenrisiko & Kannibalisierung (gering)"]},
 ],
 "notes": "Diversifikation entlang eigener Assets (Marke, Anlage, Vertrieb) — die Gastro-Basis als Testkanal zu nutzen ist der elegante Zug. Bewertet wird der Fit, nicht Fantasie-Marktgrößen."},

{"category": "growth", "framework": "Growth Framework",
 "prompt": "Dein Klient ist eine Fahrschul-Kette mit 25 Standorten. Die Nachfrage ist stabil, aber der Umsatz stagniert und die Wartezeiten für Fahrstunden sind lang. Der Inhaber will wachsen — wie strukturierst du das?",
 "qa": [
  ("Was begrenzt das Wachstum?", "Fahrlehrermangel: Stellen bleiben monatelang unbesetzt, Fahrzeuge stehen zeitweise ungenutzt."),
  ("Wie ist die Preisgestaltung?", "Eher unteres Marktniveau; die letzte Erhöhung liegt Jahre zurück, die Nachfrage übersteigt das Angebot."),
  ("Wie laufen Theorie und Verwaltung?", "Theorie klassisch in Präsenz, Terminvergabe telefonisch — digital ist wenig."),
  ("Gibt es Zusatzgeschäft?", "Kaum: keine Intensivkurse, kein B197/Automatik-Fokus, keine Firmenkooperationen."),
  ("Wie ist die Auslastung über den Tag?", "Nachmittags überbucht, vormittags schwach — Schüler wollen alle nach der Schule fahren."),
 ],
 "tree": [
  {"t": "Kapazität: Fahrlehrer", "star": True, "b": ["Rekrutierung & eigene Ausbildung finanzieren", "Bindung: Gehalt, Dienstwagenmodell, Planbarkeit"], "c": [{"t": "Vormittags-Auslastung: Erwachsene, Intensivkurse", "b": []}]},
  {"t": "Preis & Angebot", "b": ["Preiserhöhung bei Übernachfrage", "Premium-Pakete: Intensiv, Automatik, Garantie-Modelle"]},
  {"t": "Digitalisierung", "b": ["Online-Theorie & App-Buchung", "Verwaltung zentralisieren, Fahrlehrer entlasten"]},
  {"t": "Expansion", "b": ["Neue Standorte nur nach Kapazitätslösung", "Übernahme kleiner Fahrschulen (Konsolidierung)"]},
 ],
 "notes": "Wachstum bei Angebotsengpass: Erst Kapazität (Fahrlehrer, Auslastung, Digitalisierung), dann Preis nutzen, dann expandieren. 'Mehr Marketing' wäre hier die falsche Antwort."},

{"category": "growth", "framework": "Growth Framework (Ansoff-Logik)",
 "prompt": "Dein Klient ist ein Hersteller von Premium-Hundefutter mit starkem Online-Abo-Geschäft in Deutschland. Das Wachstum flacht ab. Entwickle eine Wachstumsstruktur für die nächsten drei Jahre.",
 "qa": [
  ("Wie ist das Geschäftsmodell?", "D2C-Abos mit personalisierten Futterplänen; Abo-Anteil über 80%, gute Margen."),
  ("Warum flacht das Wachstum ab?", "Die Kernzielgruppe (zahlungskräftige Hundehalter online) ist zunehmend durchdrungen, CAC steigt."),
  ("Wie ist die Kundenbindung?", "Sehr gut — Churn niedrig, hohe Weiterempfehlung."),
  ("Was gibt es außer Hundefutter?", "Nur wenige Snacks; kein Katzenfutter, kein Zubehör."),
  ("Ist der Handel eine Option?", "Bisher bewusst nicht — der Vorstand fürchtet Margenverlust und Kanalkonflikt, ist aber gesprächsbereit."),
 ],
 "tree": [
  {"t": "Bestandskunden ausschöpfen", "b": ["Cross-Sell: Snacks, Zubehör, Gesundheitsprodukte", "Preis-/Paketdifferenzierung"]},
  {"t": "Neue Segmente & Produkte", "star": True, "b": ["Katzenfutter als nächste Kategorie", "Einstiegslinie für preissensiblere Halter"], "c": [{"t": "Vet-/Spezialfutter (Allergien, Senior)", "b": []}]},
  {"t": "Neue Kanäle", "b": ["Selektiver Einzelhandel/Fachhandel als Reichweite", "Marktplätze mit Abo-Brücke"]},
  {"t": "Neue Märkte", "b": ["AT/CH als naheliegende Expansion", "Logistik & Lokalisierung prüfen"]},
 ],
 "notes": "Sättigung der Nische: Wachstum über Kategorie-Erweiterung (Katze!) und kontrollierte Kanalöffnung. Gute Antworten wägen Kanalkonflikt explizit ab statt ihn zu ignorieren."},

{"category": "growth", "framework": "Growth Framework",
 "prompt": "Dein Klient betreibt ein regionales Jobportal für Handwerks- und Logistikberufe. Es ist profitabel, wächst aber kaum noch. Große Generalisten-Portale dominieren den Markt. Wie kann das Portal wachsen?",
 "qa": [
  ("Was ist die Stärke des Portals?", "Tiefe Spezialisierung: passgenaue Kandidaten, gute Besetzungsquoten, starke Arbeitgebermarke in der Nische."),
  ("Wer zahlt und wie?", "Arbeitgeber zahlen pro Anzeige; es gibt keine Abos und kein Employer-Branding-Produkt."),
  ("Wie ist die Kandidatenseite?", "Solider Traffic über SEO und Empfehlungen, aber wenige registrierte Profile — Kandidaten kommen und gehen."),
  ("Was machen die Generalisten?", "Masse statt Klasse — in der Zielnische sind ihre Besetzungsquoten messbar schlechter."),
  ("Gibt es Expansionsideen?", "Diskutiert werden: weitere Regionen, weitere Branchen und neue Produkte — der Inhaber will Fokus."),
 ],
 "tree": [
  {"t": "Monetarisierung vertiefen", "star": True, "b": ["Abo-/Flatrate-Modelle für Vielinserenten", "Employer-Branding- & Active-Sourcing-Produkte"], "c": [{"t": "Erfolgsbasierte Modelle (Cost-per-Hire) testen", "b": []}]},
  {"t": "Kandidatenbindung", "b": ["Profile & Job-Alerts aufbauen (wiederkehrende Nutzer)", "Content/Community für Gewerke"]},
  {"t": "Geografische Expansion", "b": ["Nachbarregionen mit gleichem Playbook", "Vertrieb regional skalieren"]},
  {"t": "Fokus-Entscheidung", "b": ["Nische vertiefen statt Branchen verbreitern", "Kriterien & Sequenz festlegen"]},
 ],
 "notes": "Nischen-Marktplatz: Wachstum aus Monetarisierungstiefe + Kandidatenbindung + regionaler Replikation. Die Verbreiterung in fremde Branchen ist die Falle, die Fokus-Argumentation der Kern."},

{"category": "growth", "framework": "Growth Framework",
 "prompt": "Dein Klient ist ein mittelständischer Hersteller von Gartengeräten (Qualitätssegment), der fast nur über Baumärkte verkauft. Der Umsatz stagniert, die Baumärkte drücken die Preise. Entwickle Wachstumsoptionen.",
 "qa": [
  ("Wie abhängig ist der Klient vom Baumarkt-Kanal?", "Sehr: Drei Ketten stehen für den Großteil des Umsatzes und nutzen das in den Jahresgesprächen aus."),
  ("Wie stark ist die Marke beim Endkunden?", "Bekannt und vertraut bei der älteren Zielgruppe, bei Jüngeren kaum präsent."),
  ("Gibt es E-Commerce?", "Einen kleinen eigenen Shop ohne nennenswerten Umsatz; Marktplätze werden nicht aktiv bespielt."),
  ("Was passiert im Produktbereich?", "Akku-Geräte wachsen stark — dort ist der Klient spät dran; klassische Handgeräte sind die Basis."),
  ("Wohin will der Inhaber?", "Weniger Kanalabhängigkeit, mehr Marge, moderne Zielgruppen — ohne die Baumärkte zu verprellen."),
 ],
 "tree": [
  {"t": "Produktportfolio", "star": True, "b": ["Akku-Offensive: Plattformstrategie, Time-to-Market", "Ersatzteile & Zubehör als Margenträger"], "c": [{"t": "Services: Schärfen, Reparatur, Garantie-Plus", "b": []}]},
  {"t": "Kanal-Diversifizierung", "b": ["Eigener Shop + Marktplätze behutsam ausbauen", "Fachhandel/Gartencenter als Zweitkanal"]},
  {"t": "Marke & Zielgruppen", "b": ["Verjüngung: Content, Garten-Communities", "Urban Gardening/Balkon-Segment"]},
  {"t": "Baumarkt-Beziehung", "b": ["Kategorie-Partnerschaft statt Preisverhandlung", "Exklusive Linien je Kette gegen Konditionen"]},
 ],
 "notes": "Kanalmacht-Problem plus Technologiewandel (Akku): Wachstum = Produktoffensive + vorsichtige Kanal-Diversifizierung, ohne den Kernkanal zu sprengen. Die Balance ist der Prüfstein."},

{"category": "ma", "framework": "M&A Framework",
 "prompt": "Dein Klient ist eine Steuerberatungs-Gruppe, die durch Zukäufe kleiner Kanzleien wächst. Aktuell steht die Übernahme einer Kanzlei mit 25 Mitarbeitenden an, deren Inhaber in den Ruhestand geht. Wie prüfst du den Deal strukturiert?",
 "qa": [
  ("Warum verkauft der Inhaber?", "Altersnachfolge — er will geordnet übergeben und hängt an seinem Team und den Mandanten."),
  ("Wie loyal sind die Mandanten?", "Langjährig, aber stark auf den Inhaber persönlich bezogen — die Übergangsbegleitung ist entscheidend."),
  ("Wie steht die Kanzlei wirtschaftlich da?", "Solide Umsatzrendite, aber wenig digitalisiert und mit unterdurchschnittlichen Stundensätzen."),
  ("Wie ist das Team aufgestellt?", "Erfahren, aber zwei Leistungsträger liebäugeln mit Wechsel — Bindung ist ein Thema."),
  ("Wie wird üblicherweise bezahlt?", "Kaufpreis als Umsatz-Multiple mit Earn-out über zwei bis drei Jahre, abhängig vom Mandantenerhalt."),
 ],
 "tree": [
  {"t": "Qualität der Kanzlei", "b": ["Mandantenstruktur: Branchen, Größen, Abhängigkeiten", "Ertragsqualität & Stundensätze"]},
  {"t": "Menschen & Übergang", "star": True, "b": ["Inhaber-Übergangsphase vertraglich sichern", "Leistungsträger binden (Angebote, Perspektiven)"], "c": [{"t": "Mandanten-Kommunikation planen", "b": []}]},
  {"t": "Wertsteigerung nach Kauf", "b": ["Digitalisierung & Prozesse der Gruppe ausrollen", "Stundensätze schrittweise anheben"]},
  {"t": "Deal-Struktur", "b": ["Multiple + Earn-out an Mandantenerhalt koppeln", "Integrationsplan: Woche 1 bis Jahr 1"]},
 ],
 "notes": "People-Business-Nachfolge: Mandanten- und Mitarbeiterbindung sind der Deal — Earn-out als Absicherung. Wertsteigerungslogik (Digitalisierung, Preise) macht die Antwort rund."},

{"category": "ma", "framework": "M&A Framework",
 "prompt": "Dein Klient ist ein Anbieter von Betriebsverpflegung (Kantinen). Er kann einen Wettbewerber ähnlicher Größe übernehmen, der in einer Nachbarregion stark ist. Bewerte die Übernahme strukturiert.",
 "qa": [
  ("Was ist die strategische Logik?", "Regionale Erweiterung ohne Überschneidung plus Skaleneffekte im Einkauf und in der Verwaltung."),
  ("Wie profitabel ist das Target?", "Etwas schwächer als der Klient — vor allem wegen teurerer Wareneinsätze und älterer Verträge."),
  ("Wie sind die Kundenverträge?", "Mehrjährige Verträge mit Unternehmen und Kliniken; einige laufen im Übernahmejahr aus."),
  ("Gibt es Wechselklauseln bei Betreiberwechsel?", "Bei einem Teil der Verträge ja — Kunden könnten bei Übernahme kündigen."),
  ("Wie ähnlich sind die Betriebsmodelle?", "Ähnlich, aber unterschiedliche Küchenkonzepte und Systeme — Integration wäre echte Arbeit."),
 ],
 "tree": [
  {"t": "Strategischer Fit", "b": ["Regionale Komplementarität, keine Kannibalisierung", "Skaleneffekte: Einkauf, Verwaltung, Logistik"]},
  {"t": "Target-Qualität", "star": True, "b": ["Vertragslaufzeiten & Change-of-Control-Klauseln", "Margenlücke: Ursachen & Hebbarkeit"], "c": [{"t": "Kundenbindung im Übergang sichern", "b": []}]},
  {"t": "Synergien & Integration", "b": ["Einkaufskonditionen harmonisieren (Quick Win)", "Küchenkonzepte/Systeme: Aufwand realistisch schätzen"]},
  {"t": "Preis & Risiken", "b": ["Bewertung mit/ohne Synergien", "Schlüsselrisiko: Vertragsverluste im Jahr 1"]},
 ],
 "notes": "Konsolidierungs-Deal: Der Wert hängt an Vertragsbestand (Change-of-Control!) und hebbaren Einkaufssynergien. Wer Integrationsaufwand ehrlich einpreist, hebt sich ab."},

{"category": "ma", "framework": "M&A / Partnership Framework",
 "prompt": "Dein Klient ist ein Softwareanbieter für Zahnarztpraxen. Ein großer Dentalgeräte-Hersteller bietet an, den Klienten zu übernehmen — alternativ eine strategische Partnerschaft. Die Gründer fragen dich: Wie sollen wir diese Offerte bewerten?",
 "qa": [
  ("Was bietet der Hersteller konkret?", "Eine Vollübernahme zu attraktivem Preis — alternativ exklusive Vertriebspartnerschaft mit Minderheitsbeteiligung."),
  ("Was wollen die Gründer eigentlich?", "Wachstum beschleunigen; ein kompletter Ausstieg war nicht geplant, ist aber beim richtigen Preis diskutabel."),
  ("Welche Synergien verspricht der Hersteller?", "Zugang zu tausenden Praxen über seinen Außendienst und Bundling mit Geräten."),
  ("Was wäre der Preis der Exklusivität?", "Andere Gerätehersteller — heute Kooperationspartner — würden wohl abspringen."),
  ("Wie steht der Klient allein da?", "Profitabel wachsend, aber Vertrieb ist der Engpass; eine Finanzierungsrunde wäre die Alternative."),
 ],
 "tree": [
  {"t": "Ziele der Gründer klären", "star": True, "b": ["Exit vs. Wachstum vs. Kontrolle gewichten", "Preis-Schwelle für Vollverkauf definieren"]},
  {"t": "Option Übernahme", "b": ["Bewertung & Struktur (Earn-out, Rollen)", "Integrationsrisiko: Produktkultur im Konzern"]},
  {"t": "Option Partnerschaft", "b": ["Vertriebshebel quantifizieren (Pipeline-Zusagen)", "Exklusivität: Verlust anderer Partner einpreisen"], "c": [{"t": "Vertragsschutz: Laufzeit, Mindestumsätze, Rückfall", "b": []}]},
  {"t": "Alternative: Eigenständig", "b": ["Finanzierungsrunde + Vertriebsaufbau", "BATNA für die Verhandlung nutzen"]},
 ],
 "notes": "Optionen-Case aus Verkäufersicht: Erst Gründerziele, dann drei Optionen inkl. BATNA. Der Exklusivitäts-Preis der Partnerschaft ist die versteckte Kernfrage."},

{"category": "pricing", "framework": "Pricing Framework",
 "prompt": "Dein Klient betreibt eine Kette von Autowaschanlagen. Alle Standorte haben identische Preise, obwohl sich Lage, Wettbewerb und Auslastung stark unterscheiden. Der CEO fragt: Wie sollten wir unsere Preise gestalten?",
 "qa": [
  ("Wie ist das heutige Preissystem?", "Vier Waschprogramme mit bundesweit einheitlichen Preisen; Rabatt gibt es nur über eine selten genutzte Stempelkarte."),
  ("Wie unterschiedlich sind die Standorte?", "Stark: Innenstadtlagen mit Warteschlangen am Samstag, Landstandorte mit Leerlauf unter der Woche."),
  ("Was macht der Wettbewerb?", "Lokal sehr unterschiedlich — von Discount-Waschstraßen bis Premium-Handwäsche."),
  ("Gibt es Abo-Modelle im Markt?", "Ja, Flatrate-Abos setzen sich international durch und binden Vielwäscher."),
  ("Welche Daten liegen vor?", "Auslastung je Standort und Stunde sowie Programm-Mix sind sauber erfasst."),
 ],
 "tree": [
  {"t": "Preisdifferenzierung", "star": True, "b": ["Standort-Pricing nach Lage & Wettbewerb", "Zeitbasiert: Peak vs. Off-Peak"], "c": [{"t": "Programm-Architektur & Upsell-Treppe", "b": []}]},
  {"t": "Bindungsmodelle", "b": ["Wasch-Abo/Flatrate für Vielwäscher", "App & Loyalty statt Stempelkarte"]},
  {"t": "Zahlungsbereitschaft & Tests", "b": ["Elastizität je Standorttyp testen (Piloten)", "Wettbewerbs-Preisanker je Mikromarkt"]},
  {"t": "Umsetzung & Risiken", "b": ["Preiskommunikation & Fairness-Wahrnehmung", "Kannibalisierung Abo vs. Einzelwäsche steuern"]},
 ],
 "notes": "Einheitspreis trotz heterogener Standorte = verschenktes Geld. Standort- und Zeitdifferenzierung plus Abo-Modell sind die Kernhebel; Pilotlogik zeigt Umsetzungsreife."},

{"category": "pricing", "framework": "Pricing Framework",
 "prompt": "Dein Klient ist ein Anbieter von Online-Weiterbildungen für Pflegekräfte (B2B-Verkauf an Kliniken und Heime). Die Abschlussquoten im Vertrieb sind gut, aber der CFO glaubt, dass systematisch zu billig verkauft wird. Analysiere das Pricing.",
 "qa": [
  ("Wie wird heute bepreist?", "Preis pro Kurs und Teilnehmer mit hohen, individuell verhandelten Nachlässen — jeder Verkäufer entscheidet selbst."),
  ("Was deutet auf zu niedrige Preise hin?", "Sehr hohe Win-Rates, kaum Preis-Einwände und Wettbewerber, die für Vergleichbares spürbar mehr verlangen."),
  ("Welchen Wert stiften die Kurse?", "Sie erfüllen Pflichtfortbildungen und sparen Freistellungszeit — der Nutzen ist gut belegbar."),
  ("Gibt es Paket- oder Abomodelle?", "Nein, nur Einzelkurse; einige Großkunden fragen nach Flatrates fürs ganze Haus."),
  ("Wie reagiert der Vertrieb auf Preisprojekte?", "Skeptisch — die Provision hängt am Abschluss, nicht an der Marge."),
 ],
 "tree": [
  {"t": "Preis-Diagnose", "star": True, "b": ["Win-Rate & Rabatt-Verteilung analysieren", "Wettbewerbs- & Wertbenchmark (Freistellungskosten)"], "c": [{"t": "Zahlungsbereitschaft je Einrichtungstyp", "b": []}]},
  {"t": "Preisarchitektur", "b": ["Listenpreise & Paket-/Flatrate-Modelle je Haustyp", "Rabatt-Leitplanken statt freier Verhandlung"]},
  {"t": "Vertriebssteuerung", "b": ["Provision auf Marge/Preisqualität umstellen", "Value-Selling-Argumentarium"]},
  {"t": "Rollout", "b": ["Preiserhöhung bei Neukunden zuerst", "Bestandskunden mit Mehrwert-Story migrieren"]},
 ],
 "notes": "Underpricing-Diagnose: hohe Win-Rate + keine Einwände = klares Signal. Der Fix ist Architektur + Governance + Vertriebsanreize, nicht bloß 'Preise rauf'."},

{"category": "pricing", "framework": "Pricing Framework",
 "prompt": "Dein Klient ist ein Theater- und Konzertveranstalter mit eigenem Haus (1.200 Plätze). Viele Vorstellungen sind halb leer, Top-Acts dagegen in Minuten ausverkauft. Der Intendant möchte die Preisstrategie überarbeiten, ohne das Publikum zu verärgern.",
 "qa": [
  ("Wie wird heute bepreist?", "Feste Preiskategorien nach Sitzplatz, identisch für alle Veranstaltungen einer Sparte."),
  ("Was passiert bei ausverkauften Shows?", "Tickets landen zu Vielfachen auf Zweitmärkten — die Marge machen andere."),
  ("Wie preissensibel ist das Publikum?", "Gemischt: Stammabonnenten reagieren empfindlich auf Optik, junges Publikum vergleicht mit Streaming und Kino."),
  ("Gibt es Fördervorgaben?", "Ja, als teilgefördertes Haus muss Zugänglichkeit gewahrt bleiben — reine Gewinnmaximierung ist politisch heikel."),
  ("Welche Daten sind vorhanden?", "Verkaufsverläufe je Vorstellung und historische Auslastung liegen vollständig vor."),
 ],
 "tree": [
  {"t": "Differenzierung nach Nachfrage", "star": True, "b": ["Dynamische Korridore je Vorstellung (früh günstig)", "Top-Acts: Premiumkategorien statt Zweitmarkt-Marge"], "c": [{"t": "Schwache Termine: Last-Minute, Zielgruppenaktionen", "b": []}]},
  {"t": "Publikums- & Fairness-Logik", "b": ["Sozial-/Jugendkontingente sichtbar erhalten", "Abo-Vorteile schützen (Optik!)"]},
  {"t": "Produkt & Bundles", "b": ["Pakete: Dinner, Garderobe, Premium-Seats", "Serien-/Wahlabos für Gelegenheitsbesucher"]},
  {"t": "Umsetzung", "b": ["Pilot-Sparten & A/B-Verkaufsfenster", "Kommunikation: Mehrerlöse fördern Programm"]},
 ],
 "notes": "Revenue Management im Kulturkontext: Differenzieren ja, aber mit Fairness-Leitplanken (Förderauftrag, Abonnenten). Der Zweitmarkt-Hinweis ist der Hebel für Premium-Kategorien."},

{"category": "operations", "framework": "Operations Framework",
 "prompt": "Dein Klient ist ein Online-Händler für Autoteile. Kunden bestellen oft falsche Teile, die Retourenquote ist hoch und der Kundenservice ertrinkt in Anfragen zur Teile-Kompatibilität. Strukturiere die Verbesserung.",
 "qa": [
  ("Wie oft passen bestellte Teile nicht?", "Ein erheblicher Teil der Retouren entsteht durch Kompatibilitätsfehler — Kunden wählen das falsche Teil fürs Fahrzeug."),
  ("Wie finden Kunden heute ihre Teile?", "Über Suche und Kategorien; die Fahrzeug-Zuordnung ist unvollständig gepflegt und wird oft übersprungen."),
  ("Was kostet eine Retoure?", "Versand, Prüfung, Wiedereinlagerung — bei margenschwachen Teilen frisst eine Retoure mehrere Verkäufe auf."),
  ("Womit kämpft der Kundenservice?", "Vor allem Vorkauf-Fragen zur Passform und Nachkauf-Beschwerden — beides mit langen Antwortzeiten."),
  ("Welche Daten existieren?", "Fahrzeugdatenbanken sind lizenziert, aber nur teilweise ins Shopsystem integriert."),
 ],
 "tree": [
  {"t": "Fehlbestellungen verhindern", "star": True, "b": ["Fahrzeugidentifikation als Pflichtschritt (HSN/TSN, Kennzeichen)", "Kompatibilitätsdaten vollständig integrieren"], "c": [{"t": "Unsichere Fälle: geführte Beratung vor Kauf", "b": []}]},
  {"t": "Retourenprozess", "b": ["Ursachen-Codes erfassen & auswerten", "Schnelle Abwicklung & Wiedereinlagerung"]},
  {"t": "Kundenservice entlasten", "b": ["Self-Service: Passform-Checker, FAQ, Chatbot", "Priorisierung & Routing der Anfragen"]},
  {"t": "Steuerung", "b": ["KPI-Set: Fehlbestellquote, Kontaktrate, Retourenkosten", "Feedback-Loop in Katalogpflege"]},
 ],
 "notes": "Ursache vor Symptom: Die Retouren- und Serviceflut entsteht im Bestellprozess (Kompatibilität). Wer Prävention strukturell vor Prozessoptimierung setzt, hat den Case verstanden."},

{"category": "operations", "framework": "Operations Framework",
 "prompt": "Dein Klient ist eine Möbelspedition mit 40 Fahrzeugen, spezialisiert auf Neumöbel-Auslieferung mit Montage. Kunden beschweren sich über geplatzte Termine, und die Touren schaffen weniger Stopps als kalkuliert. Analysiere strukturiert.",
 "qa": [
  ("Wie werden Termine heute vergeben?", "Grobe Zeitfenster, telefonisch vereinbart — ohne Blick auf realistische Tourenreihenfolge."),
  ("Warum platzen Termine?", "Montagen dauern länger als geplant, Fahrzeuge stehen im Stau, und es gibt keine Echtzeit-Information an die Kunden."),
  ("Wie wird die Montagezeit kalkuliert?", "Pauschal je Möbeltyp — unabhängig von Aufwand vor Ort (Etage, Trageweg, Komplexität)."),
  ("Wie ist die Erstmontage-Qualität?", "Nachbesserungen sind häufig und blockieren Folgetouren."),
  ("Welche Systeme sind im Einsatz?", "Disposition weitgehend manuell in Excel; keine Telematik, keine Tourenoptimierung."),
 ],
 "tree": [
  {"t": "Planung & Kalkulation", "star": True, "b": ["Realistische Zeitmodelle je Auftrag (Etage, Volumen)", "Tourenoptimierung mit Software"], "c": [{"t": "Pufferlogik & dynamische Zeitfenster", "b": []}]},
  {"t": "Ausführung & Qualität", "b": ["Montage-Standards & Teamqualifikation", "Nachbesserungsquote senken (Fotos, Checklisten)"]},
  {"t": "Kundenkommunikation", "b": ["Echtzeit-Tracking & proaktive Verschiebe-Infos", "Terminbestätigung digital"]},
  {"t": "Steuerung", "b": ["KPIs: Stopps/Tour, First-Time-Right, Termintreue", "Tagessteuerung durch Disposition"]},
 ],
 "notes": "Termintreue-Case: Wurzel ist die unrealistische Planung (Pauschalzeiten), nicht die Fahrer. Software-gestützte Disposition plus Qualitätsschleife sind die Kernhebel."},

{"category": "operations", "framework": "Operations Framework",
 "prompt": "Dein Klient ist eine Stadtverwaltung, deren Bürgeramt Wartezeiten von mehreren Wochen für Termine hat (Ausweise, Ummeldungen). Der Oberbürgermeister will die Wartezeit drastisch senken — ohne nennenswert mehr Personal. Strukturiere die Analyse.",
 "qa": [
  ("Wie entstehen die Wartezeiten?", "Termin-Slots sind auf Wochen ausgebucht; gleichzeitig verfallen täglich viele Termine durch No-Shows."),
  ("Wie hoch ist die No-Show-Quote?", "Zweistellig — Erinnerungen oder einfache Stornierung gibt es nicht."),
  ("Wie unterscheiden sich die Anliegen?", "Von 5-Minuten-Abholungen bis zu komplexen Fällen — alle bekommen gleich lange Slots."),
  ("Was ist digital möglich?", "Rechtlich könnten mehrere Anliegen komplett online erledigt werden — die Stadt bietet es nur nicht an."),
  ("Wie ist die Auslastung über den Tag?", "Vormittags überlaufen, spätnachmittags Leerlauf; Samstage gibt es nicht."),
 ],
 "tree": [
  {"t": "Nachfrage senken", "star": True, "b": ["Online-Services für digitalisierbare Anliegen", "Abholung entkoppeln (Automaten, Direktausgabe)"], "c": [{"t": "No-Shows: Erinnerungen, Ein-Klick-Storno, Nachrückerliste", "b": []}]},
  {"t": "Kapazität besser nutzen", "b": ["Slot-Längen nach Anliegen differenzieren", "Randzeiten/Samstag & Springer-Pools"]},
  {"t": "Prozess & Steuerung", "b": ["Fallarten vorqualifizieren (Checklisten, Unterlagen)", "Echtzeit-Steuerung & Kennzahlen je Standort"]},
  {"t": "Umsetzung", "b": ["Quick Wins zuerst (No-Show, Slots)", "Digitalisierung als 2. Welle"]},
 ],
 "notes": "Public-Sector-Ops: Ohne Mehrpersonal zählt Nachfrage-Reduktion (online, No-Shows) vor Kapazitätsfeinschliff. Die No-Show-Quote ist der Sofort-Hebel — wer ihn findet, punktet."},

]
