# -*- coding: utf-8 -*-
# 20 neue hard-Cases im Casebook-Format.

NEW_HARD = [

{"category": "profitability", "framework": "Profitability / Turnaround Framework",
 "prompt": "Dein Klient ist eine Warenhauskette mit 35 Häusern in deutschen Innenstädten. Der Konzern verliert seit Jahren Geld; die Hälfte der Häuser ist defizitär, die Immobilien gehören teils dem Konzern, teils Vermietern. Der neue CEO will in 100 Tagen einen Sanierungsplan. Strukturiere ihn.",
 "qa": [
  ("Wie ist die Lage je Haus?", "Sehr unterschiedlich: Ein Drittel solide, ein Drittel knapp negativ, ein Drittel tiefrot — Transparenz je Haus existiert, wird aber nicht genutzt."),
  ("Wem gehören die Immobilien?", "Etwa die Hälfte Eigenbestand in teils besten Lagen; der Rest ist mit langen Verträgen gemietet."),
  ("Wie entwickelt sich der Umsatz?", "Frequenz sinkt seit Jahren; online hat die Kette kaum Relevanz, Eigenmarken sind schwach."),
  ("Welche Stakeholder sind kritisch?", "Gewerkschaft und Kommunen — Schließungen sind politisch aufgeladen; ein Sozialplan wäre teuer."),
  ("Wie viel Liquidität bleibt?", "Etwa 18 Monate bei aktuellem Verlusttempo; die Banken verlangen den Plan als Bedingung für frische Linien."),
 ],
 "tree": [
  {"t": "Portfolio-Triage", "star": True, "b": ["Häuser clustern: halten, sanieren, schließen", "Immobilienwert je Standort gegen Betriebsverlust stellen"], "c": [{"t": "Eigenimmobilien: verkaufen/umnutzen (Mixed-Use)", "b": []}]},
  {"t": "Ertragsmodell je Haus", "b": ["Flächenproduktivität: Sortimente, Untervermietung an Partner", "Lokale Formate statt Einheitswarenhaus"]},
  {"t": "Kosten & Liquidität", "b": ["Zentrale & Einkauf verschlanken", "Mietverhandlungen mit Schließungsoption als Hebel"]},
  {"t": "Stakeholder-Fahrplan", "b": ["Banken: Meilensteine & Reporting", "Sozialplan & Kommunen-Kommunikation"]},
 ],
 "notes": "Sanierungs-Case mit Immobilien-Dimension: Die Triage je Haus inkl. Immobilienwert ist der Kern — Untervermietung/Umnutzung schlägt pauschales Sparen. Liquiditäts- und Stakeholder-Logik gehören in den 100-Tage-Plan."},

{"category": "profitability", "framework": "Profitability Framework",
 "prompt": "Dein Klient ist ein Anbieter von Windpark-Wartung (O&M) in Europa. Trotz Rekord-Auftragsbestand sinkt die Marge drastisch. Verträge sind langfristig mit festen Preisen, die Kosten laufen davon. Der CEO braucht eine Struktur für das Margen-Rettungsprogramm.",
 "qa": [
  ("Wie sind die Verträge gestaltet?", "Full-Service über 10-15 Jahre mit fixen, teils unzureichend indexierten Preisen und harten Verfügbarkeitsgarantien."),
  ("Welche Kosten laufen davon?", "Technikerlöhne, Ersatzteile (v.a. Großkomponenten) und Anfahrten zu abgelegenen Parks."),
  ("Wie treffsicher ist die Kalkulation?", "Alte Verträge wurden mit optimistischen Ausfallraten kalkuliert; die Flotte altert schneller als geplant."),
  ("Gibt es Nachverhandlungsspielraum?", "Begrenzt — aber Indexklauseln, Scope-Änderungen und Laufzeitverlängerungen gegen Preisanpassung sind verhandelbar."),
  ("Wie ist die Einsatzplanung organisiert?", "Regional fragmentiert; Ferndiagnose und predictive Ansätze stecken in Pilotprojekten."),
 ],
 "tree": [
  {"t": "Vertragsportfolio", "star": True, "b": ["Marge je Vertrag: rot/gelb/grün clustern", "Nachverhandlung: Index, Scope, Laufzeit-Deals"], "c": [{"t": "Neuverträge: Kalkulation & Risikoprämien fixen", "b": []}]},
  {"t": "Servicekosten senken", "b": ["Predictive Maintenance & Ferndiagnose skalieren", "Techniker-Routen & Cluster-Einsätze"]},
  {"t": "Ersatzteile & Großkomponenten", "b": ["Einkauf bündeln, Refurbishing nutzen", "Bestands- vs. Verfügbarkeitsrisiko steuern"]},
  {"t": "Steuerung", "b": ["Verfügbarkeits-Pönalen aktiv managen", "Margen-Cockpit je Vertrag/Region"]},
 ],
 "notes": "B2B-Service mit Altvertragsfalle: Vertragsportfolio-Triage plus Nachverhandlungshebel sind der Kern; operative Effizienz (predictive, Routen) flankiert. Wer nur Kosten senkt und die Verträge ignoriert, verfehlt die Hälfte."},

{"category": "profitability", "framework": "Profitability / Pricing-Mix Framework",
 "prompt": "Dein Klient ist eine Privatklinik-Gruppe für planbare Orthopädie-Eingriffe. Auslastung und Fallzahlen steigen, doch der Gewinn stagniert. Der CFO vermutet ein Fallmix-Problem und bittet dich um eine strukturierte Analyse.",
 "qa": [
  ("Wie verdient die Gruppe Geld?", "DRG-Fallpauschalen plus Wahlleistungen (Chefarzt, Zimmer); die Pauschalen sind fix, die Kosten je Fall variieren stark."),
  ("Was hat sich im Fallmix geändert?", "Mehr komplexe Revisionen und multimorbide Patienten mit langer Verweildauer — schlecht gedeckt in den Pauschalen."),
  ("Wie sind die OP-Ressourcen ausgelastet?", "Voll — aber zunehmend mit margenschwachen Fällen; lukrative Standardeingriffe wandern zu Wettbewerbern mit kürzeren Wartezeiten."),
  ("Wie steht es um Wahlleistungen?", "Rückläufig — Ansprache und Pakete sind veraltet."),
  ("Gibt es Verhandlungsmacht bei Kassen?", "Punktuell, über Qualitätsverträge und Spezialisierungsausweise."),
 ],
 "tree": [
  {"t": "Fallmix-Transparenz", "star": True, "b": ["Deckungsbeitrag je DRG/Fallart", "Verweildauer- und Komplexitätstreiber"], "c": [{"t": "Zuweiser-Analyse: Woher kommen welche Fälle?", "b": []}]},
  {"t": "Mix aktiv steuern", "b": ["Standard-Eingriffe zurückgewinnen (Wartezeit, Pfade)", "Komplexfälle selektiv & korrekt kodiert"]},
  {"t": "Erlöse je Fall", "b": ["Wahlleistungspakete modernisieren", "Qualitäts-/Spezialverträge mit Kassen"]},
  {"t": "Kosten je Fall", "b": ["OP-Effizienz & standardisierte Pfade", "Sachkosten (Implantate) bündeln"]},
 ],
 "notes": "Profitabilität im DRG-System = Fallmix-Steuerung: Deckungsbeitrag je Fallart ist die Schlüsselanalyse, Zuweiser-Management der unterschätzte Hebel. Wer nur 'Kosten senken' strukturiert, greift zu kurz."},

{"category": "profitability", "framework": "Profitability Framework",
 "prompt": "Dein Klient ist ein SaaS-Unternehmen (Projektsteuerung für Bauträger) mit 40 Mio. € ARR, das jahrelang auf Wachstum getrimmt wurde. Die Investoren fordern jetzt 'profitables Wachstum': EBITDA-Break-even in 18 Monaten bei maximal halbiertem Wachstumstempo. Strukturiere das Programm.",
 "qa": [
  ("Wo steht das Unternehmen heute?", "ARR wächst ordentlich, EBITDA-Marge deutlich negativ — der Burn liegt im hohen einstelligen Millionenbereich pro Jahr."),
  ("Wo geht das Geld hin?", "Größter Block: Vertrieb & Marketing mit langem CAC-Payback; dazu breite Produkt-Roadmap und internationale Mini-Präsenzen ohne Traktion."),
  ("Wie gesund ist die Kundenbasis?", "Kernsegment mit exzellenter NRR; kleinere Kundensegmente churnen stark und binden Support."),
  ("Was ist tabu?", "Kernprodukt-Qualität und das Enterprise-Segment — dort entsteht der Wert."),
  ("Wie belastbar ist die Preissetzung?", "Preise seit Jahren unangetastet; Benchmarks zeigen Luft, besonders bei Bestandskunden mit hoher Nutzung."),
 ],
 "tree": [
  {"t": "Wachstumseffizienz", "star": True, "b": ["CAC-Payback je Kanal/Segment — Budget umschichten", "Fokus aufs Kernsegment (beste NRR)"], "c": [{"t": "Unprofitable Länder-Präsenzen schließen", "b": []}]},
  {"t": "Monetarisierung", "b": ["Preiserhöhung & Nutzungs-Tiers bei Bestand", "Packaging: Add-ons statt Alles-inklusive"]},
  {"t": "Kostenstruktur", "b": ["Roadmap fokussieren, Randprodukte einstellen", "Support-Aufwand der Churn-Segmente reduzieren"]},
  {"t": "Programm-Steuerung", "b": ["Break-even-Brücke: Maßnahmen quantifiziert", "Meilensteine fürs Board, Rule of 40 als Leitplanke"]},
 ],
 "notes": "Growth-to-Profit-Pivot: Die Brücke zum Break-even muss aus konkreten, quantifizierten Blöcken bestehen (Effizienz, Pricing, Fokus). Rule-of-40-Denken und Segment-Schutz (Enterprise) zeigen Klasse."},

{"category": "market_entry", "framework": "Market Entry Framework (regulierter Markt)",
 "prompt": "Dein Klient ist eine europäische Direktbank mit starkem Retail-Geschäft. Der Vorstand will in den Markt für Vermögensverwaltung einsteigen — konkret: digitale Vermögensverwaltung (Robo-Advisory) für die Massenaffluent-Kundschaft. Es gibt etablierte Robos, Banken und FinTechs. Strukturiere die Markteintrittsentscheidung.",
 "qa": [
  ("Warum will die Bank in diesen Markt?", "Zinsüberschuss-Abhängigkeit reduzieren; Provisionserträge aus dem Bestand heben — Millionen Kunden parken Geld unverzinst."),
  ("Welche Assets bringt die Bank mit?", "Große Bestandskundschaft mit App-Nutzung, Banklizenz, Vertrauen — aber keine Anlage-Beratungskompetenz im Haus."),
  ("Wie ist der Robo-Markt?", "Die Pioniere wachsen langsam und verdienen wenig; Skalenerfordernis ist hoch, Kundengewinnung teuer."),
  ("Make, Buy oder Partner?", "Alle Optionen offen: Eigenentwicklung, Übernahme eines Robos oder White-Label-Kooperation."),
  ("Welche regulatorischen Anforderungen gelten?", "Geeignetheitsprüfung, Produkt-Governance und laufende Überwachung — mit Banklizenz machbar, aber prozessintensiv."),
 ],
 "tree": [
  {"t": "Strategische Logik", "b": ["Bestandskunden-Hebel: Konversion statt teurer Akquise", "Ertragsmodell: Gebühren, Volumen, Skaleneffekte"]},
  {"t": "Eintrittsmodell", "star": True, "b": ["Make vs. Buy vs. White-Label vergleichen", "Time-to-Market & Kompetenzlücke bewerten"], "c": [{"t": "Zielbild: eigene Marke oder Sub-Brand", "b": []}]},
  {"t": "Produkt & Kunde", "b": ["Einfaches Produkt: ETF-Portfolios, klare Preise", "Onboarding im Banking-App-Flow"]},
  {"t": "Regulatorik & Risiken", "b": ["Geeignetheit & Produkt-Governance-Prozesse", "Kannibalisierung Depot-/Sparprodukte prüfen"]},
 ],
 "notes": "Der Bestandskunden-Zugang ist das eigentliche Asset — die Eintrittsfrage ist primär Make/Buy/Partner unter Zeit- und Kompetenzgesichtspunkten. Wer Robo-Ökonomie (Skalenbedarf) versteht, argumentiert realistisch."},

{"category": "market_entry", "framework": "Market Entry Framework",
 "prompt": "Dein Klient ist ein führender Anbieter von Großküchentechnik. Er beobachtet den Boom von Dark Kitchens (reine Liefer-Küchen) und überlegt, neben dem Gerätegeschäft ein eigenes 'Kitchen-as-a-Service'-Angebot zu starten: voll ausgestattete Mietküchen für Gastronomen. Bewerte den Einstieg.",
 "qa": [
  ("Wie sieht das angedachte Modell aus?", "Der Klient mietet Flächen, stattet sie mit eigener Technik aus und vermietet einsatzfertige Küchenmodule an Gastronomen und Liefermarken — inklusive Wartung."),
  ("Warum passt das zum Kerngeschäft?", "Technik, Planung und Service sind Kernkompetenz; die Geräteauslastung eigener Module wäre zudem ein Schaufenster."),
  ("Wie entwickelt sich die Nachfrage?", "Liefervolumina wachsen, aber mehrere Dark-Kitchen-Betreiber sind gescheitert — Überkapazitäten in einzelnen Städten."),
  ("Was sind die Hauptrisiken?", "Immobilien-Fixkosten und Mieterausfall; das Geschäft ist näher an Real Estate als an Maschinenbau."),
  ("Wie reagiert der Vertrieb?", "Gespalten — einige fürchten, künftig mit den eigenen Kunden (Küchenbauern, Betreibern) zu konkurrieren."),
 ],
 "tree": [
  {"t": "Marktattraktivität", "b": ["Nachfrage je Stadt: Lieferdichte, Mietniveau", "Wettbewerb & gescheiterte Modelle analysieren"]},
  {"t": "Geschäftsmodell-Design", "star": True, "b": ["Unit Economics je Modul: Miete, Auslastung, Laufzeit", "Risikoteilung: Umsatzmiete vs. Fixmiete"], "c": [{"t": "Asset-light-Variante: Partner hält Immobilie", "b": []}]},
  {"t": "Fit & Kannibalisierung", "b": ["Synergien: Technik, Service, Daten", "Kanalkonflikt mit Bestandskunden managen"]},
  {"t": "Pilot & Skalierung", "b": ["1-2 Städte, klare Erfolgskriterien", "Exit-/Umnutzungsplan je Standort"]},
 ],
 "notes": "Diversifikation Richtung Betreibermodell: Der Knackpunkt sind Unit Economics + Immobilienrisiko — asset-light-Strukturen und Risikoteilung unterscheiden reife von naiven Antworten."},

{"category": "market_entry", "framework": "Market Entry / Geographic Expansion",
 "prompt": "Dein Klient ist ein polnischer Hersteller von Fertighäusern in Holzbauweise mit exzellenter Kostenposition. Er will nach Deutschland expandieren, wo der Wohnungsbau kriselt, aber serielles Bauen politisch gefördert wird. Kommunen und Wohnungsgesellschaften suchen günstige Lösungen. Strukturiere den Markteintritt.",
 "qa": [
  ("Was kann der Klient besser als deutsche Anbieter?", "20-30% niedrigere Herstellkosten durch industrielle Fertigung und günstigere Löhne — bei solider Qualität."),
  ("Welche Segmente kommen infrage?", "Einfamilienhäuser für Private oder serieller Mietwohnungsbau für kommunale Gesellschaften — zwei sehr unterschiedliche Spiele."),
  ("Welche Zulassungen braucht es?", "Deutsche Bauartzulassungen und Nachweise; für seriellen Wohnungsbau gibt es Rahmenvereinbarungen (z.B. GdW), die Türen öffnen."),
  ("Wie wichtig ist lokale Präsenz?", "Sehr: Montageteams, Bauleitung und Gewährleistung müssen vor Ort funktionieren — sonst kein Vertrauen."),
  ("Wie ist die Wettbewerbslage?", "Deutsche Fertighaus-Anbieter sind im EFH-Premium stark; im günstigen Geschosswohnungsbau gibt es eine echte Angebotslücke."),
 ],
 "tree": [
  {"t": "Segmentwahl", "star": True, "b": ["EFH-Privatkunden vs. serieller Wohnungsbau (B2G/B2B)", "Angebotslücke: günstiger Geschosswohnungsbau"], "c": [{"t": "Rahmenvereinbarungen als Eintrittstür", "b": []}]},
  {"t": "Zulassung & Vertrauen", "b": ["Bauartzulassungen & Zertifizierungen", "Referenzprojekte mit Pilotkommunen"]},
  {"t": "Operatives Setup", "b": ["Montage-/Bauleitungsteams in DE", "Gewährleistung & Servicestruktur"]},
  {"t": "Wettbewerbsstrategie", "b": ["Kostenführerschaft in Ausschreibungen ausspielen", "Kapazitätssteuerung Werk Polen (Nachfrage-Peaks)"]},
 ],
 "notes": "Segmentwahl entscheidet: Der kommunale Serienbau spielt die Kostenstärke aus und umgeht den Marken-Nachteil im Privatgeschäft. Zulassung + lokale Ausführung sind die Glaubwürdigkeits-Hürden."},

{"category": "growth", "framework": "Growth / Platform Framework",
 "prompt": "Dein Klient ist eine Baumarktkette mit 90 Märkten und solidem Online-Shop. Der Vorstand will das Servicegeschäft rund ums Wohnen ausbauen — von Handwerkervermittlung bis Mietgeräten — und diskutiert, ob man zur 'Home-Improvement-Plattform' werden soll. Strukturiere Wachstumsoptionen und Priorisierung.",
 "qa": [
  ("Was läuft heute schon an Services?", "Geräteverleih in einigen Märkten, punktuelle Montageservices über Subunternehmer — unkoordiniert und kaum vermarktet."),
  ("Was ist die strategische Motivation?", "Produkte werden vergleichbar und margenschwach; Services versprechen Differenzierung, Frequenz und Daten."),
  ("Welche Assets hat die Kette?", "Flächendeckende Standorte, Handwerker-Kundschaft, Sortimentskompetenz und hohes Kundenvertrauen."),
  ("Wie sieht der Wettbewerb aus?", "Online-Plattformen vermitteln Handwerker, Hersteller bauen Direktservices — der Klient hat aber den physischen Zugang."),
  ("Welche Grenzen setzt der Vorstand?", "Kein Kauf großer Plattformen; Aufbau muss aus eigener Kraft mit Partnern erfolgen."),
 ],
 "tree": [
  {"t": "Service-Portfolio", "star": True, "b": ["Mietgeräte flächig skalieren (Standardisierung)", "Montage-/Installationsservices produktisieren"], "c": [{"t": "Handwerkervermittlung: Qualität & Haftung klären", "b": []}]},
  {"t": "Plattform-Logik", "b": ["Buy/Build/Partner je Service", "Digitale Buchung im Shop & Markt verzahnen"]},
  {"t": "Ökonomie & Machbarkeit", "b": ["Deckungsbeitrag je Service, Frequenz-Effekt", "Pilotmärkte & Skalierungskriterien"]},
  {"t": "Organisation", "b": ["Service-Einheit mit eigener P&L", "Partnernetz-Steuerung (SLAs, Bewertungen)"]},
 ],
 "notes": "Vom Händler zum Service-Anbieter: Priorisierung nach Asset-Fit (Mietgeräte, Montage zuerst; Vermittlung mit Qualitätsrisiko später). Plattform-Rhetorik ohne Ökonomie je Service wäre die Falle."},

{"category": "growth", "framework": "Growth Framework (B2B)",
 "prompt": "Dein Klient ist ein Spezialversicherer für Cyber-Risiken im Mittelstand. Der Markt wächst zweistellig, aber der Klient wächst langsamer als der Markt und die Schadenquoten steigen. Der CEO will profitabel Marktanteile gewinnen. Strukturiere die Wachstumsstrategie.",
 "qa": [
  ("Warum wächst der Klient langsamer als der Markt?", "Vertrieb läuft fast nur über wenige Großmakler; kleinere Makler und Direktkanäle sind unbearbeitet."),
  ("Was treibt die Schadenquote?", "Ransomware-Wellen und Kunden mit schwacher IT-Hygiene — die Risikoprüfung ist oberflächlich."),
  ("Wie ist das Produkt aufgestellt?", "Eine Einheitspolice; Prävention (Monitoring, Schulungen) wird nicht angeboten."),
  ("Was machen Wettbewerber?", "InsurTechs koppeln Versicherung an Sicherheits-Scans und Präventionsdienste — mit besseren Quoten."),
  ("Welche Kapazitäten gibt es?", "Rückversicherung ist gesichert, aber nur bei nachweislich verbesserter Risikoselektion ausbaubar."),
 ],
 "tree": [
  {"t": "Risikoselektion & Underwriting", "star": True, "b": ["Automatisierte Sicherheits-Scans im Antragsprozess", "Preis- & Annahme-Differenzierung nach IT-Reife"], "c": [{"t": "Bestand sanieren: Nachbesserungen oder Kündigung", "b": []}]},
  {"t": "Produkt & Prävention", "b": ["Versicherung + Präventionsservices bündeln", "Modulare Deckungen je Branche/Größe"]},
  {"t": "Vertrieb verbreitern", "b": ["Maklernetz jenseits der Großmakler aktivieren", "Embedded/Partner-Kanäle (IT-Dienstleister)"]},
  {"t": "Profitables Skalieren", "b": ["Schadenquote als Wachstumsvoraussetzung (Rück-Kapazität)", "Kohorten-Monitoring & Preisagilität"]},
 ],
 "notes": "Wachstum und Schadenquote hängen hier zusammen: Ohne bessere Risikoselektion keine Kapazität. Prävention als Produktbestandteil ist der strategische Zug, Vertriebsverbreiterung der Volumenhebel."},

{"category": "growth", "framework": "Growth / Internationalisierung",
 "prompt": "Dein Klient ist ein D2C-Kosmetikunternehmen (vegane Hautpflege) mit 60 Mio. € Umsatz, stark auf Instagram/TikTok gewachsen. Das DACH-Wachstum flacht ab, Paid-Social wird teurer. Der Beirat fordert einen Plan: In drei Jahren 150 Mio. € Umsatz. Strukturiere die Wachstumsstrategie.",
 "qa": [
  ("Woher kommt das heutige Geschäft?", "Fast alles D2C online in DACH; Retail nur ein Testlisting, internationale Umsätze minimal."),
  ("Wie entwickeln sich die Marketingkosten?", "CAC über Paid Social hat sich in zwei Jahren fast verdoppelt; organische Reichweite trägt noch, skaliert aber nicht beliebig."),
  ("Wie stark ist die Marke?", "In der Zielgruppe DACH sehr stark (Community, Wiederkauf); außerhalb unbekannt."),
  ("Was ist mit Retail?", "Drogerieketten haben Interesse signalisiert — der Beirat ist gespalten (Marge vs. Reichweite)."),
  ("Wie sieht das Sortiment aus?", "Fokussiert auf Gesichtspflege; Körperpflege, Sonnenschutz und Männerlinie fehlen."),
 ],
 "tree": [
  {"t": "Kanal-Expansion", "star": True, "b": ["Retail-Eintritt (Drogerie): Reichweite vs. Margen-/Kanalkonflikt", "Amazon & Marktplätze kontrolliert"], "c": [{"t": "D2C-Effizienz: CRM, Abo, Community statt Paid-Only", "b": []}]},
  {"t": "Sortiment & Preisarchitektur", "b": ["Kategorie-Erweiterung (Körper, Sonne)", "Hero-Produkte & Bundles für AOV"]},
  {"t": "Internationalisierung", "b": ["1-2 EU-Märkte mit Playbook (nicht flächig)", "Lokalisierung: Influencer, Regulatorik"]},
  {"t": "Zielpfad 150 Mio.", "b": ["Wachstumsbrücke je Hebel quantifizieren", "Meilensteine & Investitionsbedarf"]},
 ],
 "notes": "Die 150-Mio.-Brücke braucht mehrere Hebel: Retail ist der große Reichweiten-Schritt (Kanalkonflikt abwägen!), plus Sortiment und selektive Internationalisierung. Eine quantifizierte Brücke adelt die Antwort."},

{"category": "growth", "framework": "Growth / Ecosystem Framework",
 "prompt": "Dein Klient ist ein Landmaschinenhändler-Verbund (12 Standorte), der Traktoren und Erntemaschinen eines großen Herstellers vertreibt. Neumaschinen-Margen sinken, Landwirte investieren zögerlicher. Der Verbund sucht Wachstum jenseits des Neumaschinenverkaufs. Entwickle die Struktur.",
 "qa": [
  ("Wie verteilt sich das Geschäft heute?", "Großteil Neumaschinen (margenschwach), dazu Werkstatt, Ersatzteile und etwas Gebrauchtgeschäft — Service ist profitabel, aber unterentwickelt."),
  ("Wie ist die Kundenbindung?", "Über den Standort stark, aber unsystematisch: keine Wartungsverträge, kein aktives Bestandsmanagement der Maschinenflotte."),
  ("Welche Trends verändern den Markt?", "Precision Farming (GPS, Datendienste), Miet-/Sharing-Modelle für teure Erntetechnik und wachsender Gebrauchtmarkt."),
  ("Was erlaubt der Hersteller?", "Service, Gebraucht, Vermietung und Datendienste sind frei gestaltbar; Fremdmarken im Neugeschäft nicht."),
  ("Wie ist die Kapitallage?", "Solide — Investitionen in Mietflotte oder Übernahmen kleinerer Händler sind möglich."),
 ],
 "tree": [
  {"t": "Service & Aftermarket", "star": True, "b": ["Wartungsverträge & Winter-Checks systematisieren", "Ersatzteil-Verfügbarkeit & Express-Logistik"], "c": [{"t": "Flottenbestand aktiv managen (wer fährt was, wann fällig)", "b": []}]},
  {"t": "Miete & Gebraucht", "b": ["Mietflotte für Erntespitzen aufbauen", "Gebraucht professionalisieren (Ankauf, Aufbereitung, Export)"]},
  {"t": "Precision-Farming-Dienste", "b": ["Nachrüstung, Einrichtung, Schulung als Service", "Datendienste mit Hersteller bündeln"]},
  {"t": "Struktur & Skalierung", "b": ["Verbund-Synergien: Zentrale Disposition, Einkauf", "Zukauf kleiner Händler (Konsolidierung)"]},
 ],
 "notes": "Vom Verkäufer zum Lebenszyklus-Partner: Service-Systematisierung ist der sichere Kern, Miete/Gebraucht und Precision-Dienste die Wachstumsflächen. Herstellergrenzen (kein Fremd-Neugeschäft) beachten."},

{"category": "ma", "framework": "M&A / Carve-out Framework",
 "prompt": "Dein Klient ist ein Chemiekonzern, der sein margenschwaches Additiv-Geschäft (600 Mio. € Umsatz) verkaufen will. Interessenten: ein Wettbewerber und zwei PE-Fonds. Das Geschäft teilt Standorte, IT und Vertrieb mit dem Konzern. Strukturiere Verkaufsvorbereitung und Prozess.",
 "qa": [
  ("Warum wird verkauft?", "Portfolio-Fokus auf Hochmargen-Spezialitäten; das Additiv-Geschäft braucht Investitionen, die der Konzern woanders einsetzen will."),
  ("Wie verflochten ist das Geschäft?", "Stark: Zwei von vier Produktionslinien teilen Standorte, Vertrieb läuft über gemeinsame Key Accounts, IT/ERP ist konzernweit."),
  ("Was bedeutet das für den Verkauf?", "Ohne Carve-out-Konzept (Standalone-Kosten, Übergangsverträge) sind Bewertungen der Bieter kaum belastbar."),
  ("Wie performt das Geschäft?", "Stabile Umsätze, Marge unter Konzernschnitt — mit klarem Kostensenkungspotenzial, das der Konzern nie priorisiert hat."),
  ("Welche Sensibilitäten gibt es?", "Kunden-Doppelbeziehungen (kaufen auch andere Konzernprodukte) und Betriebsrats-Themen an geteilten Standorten."),
 ],
 "tree": [
  {"t": "Carve-out-Design", "star": True, "b": ["Perimeter: Was gehört dazu (Anlagen, Patente, Leute)?", "Standalone-Kosten & TSAs (IT, Standort, Vertrieb)"], "c": [{"t": "Entflechtungs-Roadmap vor Signing", "b": []}]},
  {"t": "Equity Story & Wert", "b": ["Kostenpotenzial als Upside dokumentieren", "Bewertungsspanne & Stapled-Finanzierung"]},
  {"t": "Prozess & Bieter", "b": ["Stratege (Synergien, Kartellrisiko) vs. PE (Preis, TSA-Appetit)", "Wettbewerblicher Prozess, saubere Datenraum-Basis"]},
  {"t": "Stakeholder & Kontinuität", "b": ["Key Accounts: Lieferbeziehungen absichern", "Betriebsrat & Standortvereinbarungen"]},
 ],
 "notes": "Carve-out-Verkauf: Ohne Perimeter/TSA-Klarheit keine validen Gebote — das ist der Kern. Bieter-Differenzierung (Stratege vs. PE) und Kundenkontinuität runden die Struktur ab."},

{"category": "ma", "framework": "M&A / Joint Venture Framework",
 "prompt": "Dein Klient ist ein Energieversorger, der mit einem Immobilienkonzern ein Joint Venture für Mieterstrom und Gebäude-Photovoltaik gründen will. Beide bringen Assets ein, die Governance ist strittig. Bewerte das Vorhaben und strukturiere die JV-Entscheidung.",
 "qa": [
  ("Was soll das JV konkret machen?", "PV-Anlagen auf den Beständen des Immobilienpartners bauen und Mieterstrom vermarkten — später Drittkunden."),
  ("Was bringt jede Seite ein?", "Der Versorger: Technik, Energiehandel, Abrechnung, Regulatorik-Know-how. Der Immobilienkonzern: Dachflächen, Mieterzugang, Kapitalanteil."),
  ("Wo hakt die Governance?", "Beide wollen 51% und den CEO stellen; strittig sind auch Exklusivität und Drittgeschäft."),
  ("Wie attraktiv ist die Ökonomie?", "Solide Renditen je Objekt, aber stark abhängig von Regulatorik (Mieterstromzuschlag) und Skaleneffekten im Rollout."),
  ("Was wäre die Alternative zum JV?", "Ein reiner Liefer-/Dienstleistungsvertrag ohne gemeinsame Gesellschaft — weniger Upside, weniger Konfliktpotenzial."),
 ],
 "tree": [
  {"t": "Strategische Logik", "b": ["Komplementarität der Assets prüfen", "Marktpotenzial & Rollout-Geschwindigkeit"]},
  {"t": "JV-Design", "star": True, "b": ["Governance: Anteile, Vetos, Deadlock-Mechanismen", "Exklusivität & Drittgeschäft regeln"], "c": [{"t": "Einbringungswerte fair bewerten", "b": []}]},
  {"t": "Ökonomie & Risiken", "b": ["Business Case je Objekt & Skalenpfad", "Regulatorik-Szenarien (Förderung ändert sich)"]},
  {"t": "Alternativen & Exit", "b": ["JV vs. Vertragsmodell vergleichen", "Exit-/Buy-out-Klauseln von Anfang an"]},
 ],
 "notes": "JV-Cases entscheiden sich am Design: Governance (Deadlock!), Exklusivität und Exit-Klauseln sind wichtiger als die reine Marktstory. Die Vertragsalternative als BATNA zeigt Verhandlungsreife."},

{"category": "ma", "framework": "M&A Framework (Tech-Akquisition)",
 "prompt": "Dein Klient ist ein börsennotierter Personaldienstleister. Um dem Margendruck zu entgehen, will der CEO eine HR-Tech-Plattform (Freelancer-Management-System, 25 Mio. € ARR, wachstumsstark, unprofitabel) für einen hohen Preis übernehmen. Der Aufsichtsrat ist skeptisch. Strukturiere die Entscheidungsvorlage.",
 "qa": [
  ("Was ist die strategische These?", "Verschiebung vom margenschwachen Verleihgeschäft zur skalierbaren Software — die Plattform würde Kunden und Freelancer digital binden."),
  ("Warum ist der Aufsichtsrat skeptisch?", "Preis (zweistelliges ARR-Multiple), Kulturunterschied und die Historie: Zwei frühere Digital-Zukäufe sind gescheitert."),
  ("Wie solide ist das Target?", "Starkes Produkt, gute Kundenbindung, aber hoher Burn und Abhängigkeit vom Gründerteam."),
  ("Welche Synergien sind realistisch?", "Cross-Sell in die Konzern-Kundenbasis und Nutzung der Plattform für den eigenen Freelancer-Pool — quantifiziert hat das noch niemand."),
  ("Wie soll integriert werden?", "Offen — von voller Integration bis 'Standalone mit Brücken' ist alles denkbar."),
 ],
 "tree": [
  {"t": "Strategische These prüfen", "star": True, "b": ["Zielbild: Dienstleister mit Software oder Software-Firma?", "Synergien hart quantifizieren (Cross-Sell, Eigenumsatz)"], "c": [{"t": "Lehren aus gescheiterten Digital-Zukäufen", "b": []}]},
  {"t": "Target-Qualität", "b": ["Produkt, Kohorten, Churn, Burn", "Gründerbindung & Schlüsselteam"]},
  {"t": "Preis & Struktur", "b": ["Bewertung vs. SaaS-Benchmarks, Earn-out", "Kapitalmarkt-Story (Verwässerung, Guidance)"]},
  {"t": "Integrationsmodell", "b": ["Standalone mit Brücken statt Vollintegration", "Governance & Anreize fürs Zielteam"]},
 ],
 "notes": "Transformation-durch-Akquisition: Die Entscheidungsvorlage braucht harte Synergie-Quantifizierung und ein Integrationsmodell, das das Asset nicht zerstört (Standalone-Logik). Die gescheiterte Historie explizit adressieren."},

{"category": "pricing", "framework": "Pricing / Monetization Framework",
 "prompt": "Dein Klient ist ein Verkehrsverbund, der ein neues Tarifsystem einführen will: weg vom Zonen-Dschungel, hin zu einem einfachen, digitalen Modell (Luftlinien- oder Capping-Tarif). Ziel: mehr Fahrgäste, stabile Einnahmen, politische Zustimmung. Strukturiere die Tarifreform.",
 "qa": [
  ("Was ist am heutigen System das Problem?", "Dutzende Zonen und Ticketarten — Gelegenheitskunden verstehen es nicht und fahren seltener oder schwarz."),
  ("Welche Modelle stehen zur Debatte?", "Luftlinien-Preis je Fahrt oder Check-in/Check-out mit Tages-/Monats-Capping wie in London."),
  ("Welche Einnahmen-Restriktion gilt?", "Die Einnahmen der Verbundpartner dürfen im Übergangsjahr höchstens leicht sinken — es gibt einen Ausgleichsmechanismus."),
  ("Wie ist die digitale Ausstattung?", "Die App ist verbreitet, aber Barzahler und Senioren müssen weiter bedient werden."),
  ("Wer entscheidet am Ende?", "Die Verbandsversammlung der Kommunen — politische Vermittelbarkeit ist ein hartes Kriterium."),
 ],
 "tree": [
  {"t": "Tarifdesign", "star": True, "b": ["Modelle vergleichen: Luftlinie vs. Capping", "Einfachheit als Kernziel (verstehbar in 1 Satz)"], "c": [{"t": "Preispunkte & Capping-Schwellen kalibrieren", "b": []}]},
  {"t": "Einnahmen-Simulation", "b": ["Gewinner/Verlierer-Analysen je Kundengruppe", "Elastizität: Mehrfahrten vs. Preis je Fahrt"]},
  {"t": "Zugänglichkeit & Fairness", "b": ["Nicht-Digital-Lösungen (Karte, Vertrieb)", "Sozialtarife & Pendler-Schutz"]},
  {"t": "Politik & Umsetzung", "b": ["Pilotphase & transparente Evaluation", "Ausgleichsmechanik zwischen Verbundpartnern"]},
 ],
 "notes": "Tarifreform = Pricing unter politischen Nebenbedingungen: Einnahmen-Simulation mit Gewinner/Verlierer-Logik ist Pflicht, Einfachheit das Leitkriterium. Wer Nicht-Digital-Kunden vergisst, scheitert politisch."},

{"category": "pricing", "framework": "Pricing Framework (B2B-Verhandlung)",
 "prompt": "Dein Klient ist ein Zulieferer für die Lebensmittelindustrie (Aromen und Extrakte). Der größte Kunde — ein multinationaler Konzern — fordert in der Jahresverhandlung 8% Preissenkung und droht mit Dual Sourcing. Der Klient hat selbst Kostensteigerungen. Strukturiere Verhandlungsstrategie und Preisarchitektur.",
 "qa": [
  ("Wie wichtig ist der Kunde?", "Rund 25% des Umsatzes über mehrere Werke und Rezepturen — ein Verlust wäre schwer, aber nicht existenzbedrohend."),
  ("Wie austauschbar sind die Produkte?", "Gemischt: Einige Standard-Extrakte sind substituierbar, mehrere Schlüsselaromen sind in Kundenrezepturen designt und qualifiziert — ein Wechsel dauert dort 12-18 Monate."),
  ("Wie ist die eigene Kostenlage?", "Rohstoffe und Energie deutlich gestiegen; die aktuelle Kundenmarge ist bereits unter Portfolio-Schnitt."),
  ("Was weiß man über die Gegenseite?", "Der Einkauf fährt ein konzernweites Kostenprogramm; Qualität und Liefertreue des Klienten werden intern hoch geschätzt."),
  ("Welche Zugeständnisse wären denkbar?", "Volumenbündelung, längere Laufzeiten, gemeinsame Effizienzprojekte — reine Preisnachlässe will der CEO vermeiden."),
 ],
 "tree": [
  {"t": "Verhandlungs-Vorbereitung", "star": True, "b": ["Produkt-Matrix: substituierbar vs. designed-in", "Eigene BATNA & Kundenkosten eines Wechsels"], "c": [{"t": "Verhandlungsziele & Walk-away je Produktgruppe", "b": []}]},
  {"t": "Preisarchitektur", "b": ["Differenzierte Antwort statt pauschal -8%", "Indexierung (Rohstoffe) & Gleitklauseln einbauen"]},
  {"t": "Wert statt Preis", "b": ["Effizienz-/Reformulierungsprojekte anbieten", "Bündelung, Laufzeit, Exklusivität als Währung"]},
  {"t": "Risiko & Nachspiel", "b": ["Dual-Sourcing-Szenario planen (Kapazität, Mix)", "Kundenabhängigkeit mittelfristig senken"]},
 ],
 "notes": "B2B-Preisverhandlung: Die Produkt-Matrix (wo hat wer Macht?) ist das Herzstück — pauschale Zugeständnisse sind der Fehler. Wert-Zugeständnisse statt Preis und Indexierung zeigen Pricing-Reife."},

{"category": "pricing", "framework": "Pricing / Freemium Framework",
 "prompt": "Dein Klient betreibt eine Fitness- und Ernährungs-App mit 4 Mio. registrierten Nutzern, davon zahlen 3% für Premium. Investoren fordern deutlich mehr Umsatz. Das Team streitet: Paywall härter ziehen, Preise erhöhen oder Werbung einführen? Strukturiere die Monetarisierungsstrategie.",
 "qa": [
  ("Wie sieht das heutige Freemium aus?", "Sehr großzügig: Tracking, Rezepte und Basis-Pläne sind gratis; Premium bietet Personalisierung und Detailauswertungen."),
  ("Was weiß man über die Zahler?", "Sie konvertieren meist in den ersten Wochen, churnen aber nach Jahreszahlung stark; Conversion-Treiber sind Trainingspläne."),
  ("Wie reagieren Nutzer auf Paywall-Tests?", "Ein kleiner Test mit härterer Paywall hob die Conversion, senkte aber Neuregistrierungen über Word-of-Mouth."),
  ("Ist Werbung eine Option?", "Möglich, aber die Marke ist werbefrei positioniert; das Team fürchtet Nutzerverärgerung und Downloads-Verlust."),
  ("Gibt es B2B-Ideen?", "Krankenkassen und Arbeitgeber haben Interesse an Firmenlizenzen signalisiert — bislang unbearbeitet."),
 ],
 "tree": [
  {"t": "Freemium-Architektur", "star": True, "b": ["Free/Premium-Grenze neu ziehen (Wert vs. Viralität)", "Conversion-Momente gezielt monetarisieren (Pläne)"], "c": [{"t": "A/B-Roadmap statt Big-Bang-Paywall", "b": []}]},
  {"t": "Preis & Pakete", "b": ["Preistests je Markt/Kohorte", "Tiers: Monat/Jahr, Bundles (Coaching, Familie)"]},
  {"t": "Zusätzliche Erlösquellen", "b": ["B2B: Kassen-/Arbeitgeberlizenzen", "Werbung nur als klar getrenntes Free-Erlebnis prüfen"]},
  {"t": "Retention der Zahler", "b": ["Jahres-Churn: Engagement-Programm vor Renewal", "Winback & Pausen-Angebote"]},
 ],
 "notes": "Freemium-Monetarisierung ist Architektur-Arbeit: Die Free-Grenze bestimmt Conversion UND Wachstum — Trade-off explizit machen. B2B ist die unterschätzte Erlösquelle, Zahler-Churn der stille Hebel."},

{"category": "operations", "framework": "Operations / Supply Chain Framework",
 "prompt": "Dein Klient ist ein Hersteller von Elektro-Kleingeräten mit Fertigung in China und Vertrieb in Europa. Nach mehreren Lieferkrisen (Frachtraten, Lockdowns, Rotes Meer) fordert der Aufsichtsrat eine widerstandsfähigere Lieferkette — ohne die Kostenposition zu ruinieren. Strukturiere das Resilienz-Programm.",
 "qa": [
  ("Wie ist die Kette heute aufgebaut?", "Zwei Vertragsfertiger in China, Seefracht nach Rotterdam, ein Zentrallager für Europa — kostenoptimal, aber ohne Redundanz."),
  ("Was haben die Krisen konkret gekostet?", "Umsatzausfälle durch Out-of-Stock in Peak-Saisons und teure Luftfracht-Notfälle — zusammen ein mittlerer siebenstelliger Betrag in drei Jahren."),
  ("Welche Produkte sind kritisch?", "Ein Drittel des Sortiments bringt 80% des Deckungsbeitrags — dort tut ein Ausfall richtig weh."),
  ("Welche Alternativen wurden geprüft?", "Erste Gespräche mit Fertigern in Vietnam und der Türkei; Nearshoring wäre je Einheit teurer, aber schneller."),
  ("Welche Rolle spielt Bestandspolitik?", "Bestände wurden aus Cash-Gründen minimiert — Sicherheitsbestände existieren faktisch nicht."),
 ],
 "tree": [
  {"t": "Risiko-Transparenz", "b": ["Kritikalitäts-Matrix: Produkte x Ausfallkosten", "Single Points of Failure kartieren"]},
  {"t": "Sourcing-Strategie", "star": True, "b": ["Dual Sourcing für A-Produkte (China+1)", "Nearshoring selektiv (Türkei) für Reaktionsfähigkeit"], "c": [{"t": "TCO-Vergleich statt Stückkosten-Fixierung", "b": []}]},
  {"t": "Puffer & Logistik", "b": ["Differenzierte Sicherheitsbestände (A-Artikel)", "Frachtmix & Routen-Alternativen vertraglich sichern"]},
  {"t": "Steuerung & Frühwarnung", "b": ["Szenario-Playbooks & Eskalationslogik", "Resilienz-KPIs neben Kosten-KPIs"]},
 ],
 "notes": "Resilienz vs. Kosten: differenzieren statt pauschal — China+1 und Puffer nur für kritische A-Produkte, bewertet über TCO inkl. Ausfallkosten. Wer alles absichern will, hat den Trade-off nicht verstanden."},

{"category": "operations", "framework": "Operations Framework (Service)",
 "prompt": "Dein Klient ist eine Bank, deren Baufinanzierungs-Bearbeitung von Antrag bis Zusage im Schnitt 18 Arbeitstage dauert — Vermittler geben Kunden zunehmend an schnellere Wettbewerber (unter 5 Tagen). Der Vorstand will unter eine Woche kommen, ohne die Risikostandards zu senken. Strukturiere das Vorhaben.",
 "qa": [
  ("Wo bleibt die Zeit liegen?", "Vor allem in Liegezeiten: unvollständige Unterlagen, Rückfragen-Schleifen mit Vermittlern und Warteschlangen vor der Votierung — die reine Bearbeitungszeit ist kurz."),
  ("Wie kommen Anträge herein?", "Zu einem großen Teil über Vermittlerplattformen, oft unvollständig; eine verbindliche Unterlagen-Checkliste fehlt."),
  ("Wie ist die Bearbeitung organisiert?", "Funktional zerschnitten: Datenerfassung, Marktfolge, Votum, Beschlussfertigung — mit Übergaben und Medienbrüchen."),
  ("Was ist automatisierbar?", "Haushaltsrechnung, Objektbewertung (bei Standardobjekten) und Unterlagenprüfung sind technisch weitgehend automatisierbar."),
  ("Welche Fälle sind Standard?", "Gut die Hälfte: angestellte Kunden, Standardobjekt, klare Beleihung — der Rest ist komplex (Selbstständige, Sonderobjekte)."),
 ],
 "tree": [
  {"t": "Fall-Segmentierung", "star": True, "b": ["Fast Lane für Standardfälle (>50%)", "Komplexfälle mit Experten-Team"], "c": [{"t": "Automatisierte Vorprüfung & Dunkelverarbeitung", "b": []}]},
  {"t": "Eingangsqualität", "b": ["Verbindliche digitale Checklisten für Vermittler", "Vollständigkeit als Annahme-Gate + Statusportal"]},
  {"t": "Prozess & Organisation", "b": ["End-to-End-Teams statt Funktions-Silos", "Liegezeiten & Warteschlangen steuern (Takt, WIP-Limits)"]},
  {"t": "Risiko & Steuerung", "b": ["Standards unangetastet: Kompetenzen klar regeln", "Durchlaufzeit-KPI je Segment & Vermittler-SLA"]},
 ],
 "notes": "Durchlaufzeit-Case: Liegezeiten schlagen Bearbeitungszeit — Segmentierung (Fast Lane) plus Eingangsqualität sind die großen Hebel. 'Mehr Personal' wäre die falsche, 'Risikostandards lockern' die verbotene Antwort."},

{"category": "operations", "framework": "Operations / Netzwerk Framework",
 "prompt": "Dein Klient ist ein Anbieter von Paketstationen, der sein Netz in drei Jahren von 2.000 auf 10.000 Automaten ausbauen will. Schon heute hakt es: Aufbau-Rückstände, Vandalismus-Ausfälle und unrentable Standorte. Der COO fragt: Wie skalieren wir das Netz profitabel?",
 "qa": [
  ("Wie werden Standorte heute ausgewählt?", "Opportunistisch — wo Partner (Supermärkte, Wohnungswirtschaft) Flächen anbieten; eine datenbasierte Standortbewertung fehlt."),
  ("Was macht einen Standort rentabel?", "Paketvolumen pro Automat — getrieben von Wohndichte, Carrier-Anbindung und Sichtbarkeit; ein Fünftel der Standorte liegt weit unter Plan."),
  ("Woran hakt der Aufbau?", "Genehmigungen, Stromanschlüsse und knappe Montagetrupps — die Pipeline ist voll, aber der Durchsatz niedrig."),
  ("Wie schlimm sind die Ausfälle?", "Vandalismus und Technikdefekte legen Automaten teils wochenlang lahm — Ersatzteile und Techniker sind der Engpass."),
  ("Wie ist das Verhältnis zu den Carriern?", "Mehrere Carrier nutzen das Netz; die Verträge honorieren Volumen, nicht Verfügbarkeit."),
 ],
 "tree": [
  {"t": "Standort-Strategie", "star": True, "b": ["Datenbasiertes Scoring (Dichte, Frequenz, Carrier)", "Bestands-Triage: Underperformer versetzen/kündigen"], "c": [{"t": "Partner-Pipelines priorisieren statt Opportunismus", "b": []}]},
  {"t": "Rollout-Maschine", "b": ["Standardisierte Aufbau-Kits & Genehmigungs-Playbooks", "Montagekapazität skalieren (Partnerfirmen, Takt)"]},
  {"t": "Betrieb & Verfügbarkeit", "b": ["Predictive Maintenance & Ersatzteil-Logistik", "Vandalismus: Härtung, Standortwahl, Versicherung"]},
  {"t": "Ökonomie & Verträge", "b": ["Unit Economics je Automat als Steuerungsgröße", "Carrier-Verträge: Verfügbarkeits-Anreize"]},
 ],
 "notes": "Skalierung = Wiederholbarkeit: Standort-Scoring und eine industrialisierte Rollout-Maschine sind der Kern; Betrieb (Verfügbarkeit) entscheidet über die Ökonomie. Wer nur 'schneller bauen' sagt, skaliert die Probleme mit."},

]
