# -*- coding: utf-8 -*-
"""Creativity-Drill v3: simple Business-Sense-Brainstorms.
- MEDIUM_REFS: Referenz-Ideen fuer die 30 bestehenden medium-Einzeiler
  (prompt = exakter DB-Text als UPDATE-Schluessel, NICHT aendern!)
- HARD_CASES: 30 neue hard-Fragen — etwas breiter als medium, aber simpel:
  1-2 kurze Saetze, kein Zahlen-Kontext, nichts zu rechnen.
Referenz-Format je Case: Zeilen "• Kategorie: Idee, Idee, Idee" — dient als
Beispiel-Loesung im Result und als Referenz fuer den KI-Grader.
"""

MEDIUM_REFS = [
    # ---------- MARKET ENTRY (10) ----------
    {"prompt": "Welche Optionen hat eine deutsche Buchhandelskette, um nach Italien zu expandieren?",
     "ref": "• Organisch: eigene Filialen in Mailand/Rom testen, italienischer Online-Shop\n• Partnerschaften: Shop-in-Shop mit italienischen Kaufhäusern, Kooperation mit lokalen Verlagen\n• Anorganisch: Übernahme einer kleinen italienischen Kette, Joint Venture\n• Leicht testen: Pop-up-Stores, deutschsprachige Nische (Touristen, Expats) zuerst"},
    {"prompt": "Wie kann eine spanische Olivenöl-Manufaktur in den deutschen Premium-Lebensmittelmarkt eintreten?",
     "ref": "• Handel: Listung bei Feinkost-Händlern und Bio-Ketten, Delikatess-Abteilungen der Kaufhäuser\n• Direkt: eigener Online-Shop, Abo-Modell, Amazon/Marktplätze\n• Gastronomie: Partnerschaften mit Restaurants als Referenz und Vertriebskanal\n• Marke: Verkostungen, Food-Messen, Kooperation mit Koch-Influencern"},
    {"prompt": "Welche Wege hat ein britisches Friseur-Salon-Franchise, um in den niederländischen Markt zu expandieren?",
     "ref": "• Franchise: lokale Franchise-Nehmer rekrutieren, Master-Franchise für NL vergeben\n• Eigenbetrieb: Flagship-Salons in Amsterdam/Rotterdam als Leuchttürme\n• Anorganisch: Übernahme lokaler Salon-Ketten und Umflaggen\n• Risikoarm: Pilot mit 1-2 Standorten, Partnerschaft mit Drogerie-/Beauty-Ketten"},
    {"prompt": "Welche Optionen hat ein deutscher Hersteller von Elektro-Lastenrädern, um den französischen Markt zu erschließen?",
     "ref": "• Vertrieb: französische Fahrradhändler als Partner, eigener Online-Direktvertrieb\n• B2B: Flottenkunden (Lieferdienste, Kommunen, Handwerker) direkt ansprechen\n• Präsenz: Showrooms in Paris/Lyon, Messen und Test-Events\n• Strukturen: lokaler Distributor vs. eigene Vertriebstochter, Leasing-Partnerschaften"},
    {"prompt": "Wie kann eine schweizerische Schokoladen-Boutique-Kette in den US-Markt eintreten?",
     "ref": "• Eigenbetrieb: Flagship in New York, weitere Boutiquen in Premium-Lagen\n• Handel: Listung bei Premium-Retailern (Whole Foods, Kaufhäuser), Duty-Free\n• Online: US-Webshop, Geschenk-/Corporate-Geschäft, Abo-Boxen\n• Partner: Franchise/Lizenz, Kooperation mit Hotels und Airlines"},
    {"prompt": "Welche Wege hat ein polnischer Bio-Kosmetik-Hersteller, um nach Skandinavien zu expandieren?",
     "ref": "• Handel: Listung bei Drogerie-/Apothekenketten, Bio-Fachhandel\n• Online: eigene Shops je Land, nordische Beauty-Marktplätze, Amazon\n• Marke: Zertifizierungen (Nordic Swan) als Türöffner, Influencer-Kooperationen\n• Partner: lokaler Distributor zuerst, später eigene Ländergesellschaft"},
    {"prompt": "Welche Optionen hat eine österreichische Yoga-Studio-Kette, um in den deutschen Markt einzutreten?",
     "ref": "• Eigenbetrieb: Studios in Großstädten mit hoher Yoga-Dichte (Berlin, München)\n• Franchise: deutsche Franchise-Partner, Master-Franchise je Region\n• Anorganisch: Übernahme bestehender Studios, Umflaggen\n• Digital/leicht: Online-Kurse als Markenaufbau, Pop-up-Kurse, Firmen-Yoga (B2B)"},
    {"prompt": "Wie kann ein niederländischer Anbieter von Photovoltaik-Anlagen den deutschen Privatkunden-Markt erschließen?",
     "ref": "• Vertrieb: lokale Installateur-Partnernetzwerke, eigene Vertriebsteams je Region\n• Digital: Online-Konfigurator und Lead-Generierung, Vergleichsportale\n• Partner: Kooperation mit Energieversorgern, Baumärkten, Fertighaus-Anbietern\n• Angebot: Miet-/Abo-Modelle statt Kauf als Differenzierung"},
    {"prompt": "Welche Wege hat eine französische Patisserie-Kette, um nach Japan zu expandieren?",
     "ref": "• Partner: Joint Venture mit japanischem Handelshaus, Lizenzpartner mit Lokal-Know-how\n• Handel: Corner in Depachika (Kaufhaus-Food-Hallen) — klassischer Einstieg für Premium-Patisserie\n• Eigenbetrieb: Flagship in Tokio (Ginza) als Markenanker\n• Anpassung: limitierte Editionen und lokale Geschmäcker, Geschenk-Kultur bedienen"},
    {"prompt": "Welche Optionen hat ein deutscher Hersteller von Outdoor-Bekleidung, um in den chinesischen Markt einzusteigen?",
     "ref": "• Digital first: Tmall/JD-Flagship-Stores, Social Commerce (WeChat, Douyin), lokale KOL\n• Handel: Listung bei Sport-/Outdoor-Ketten, Shop-in-Shop\n• Partner: lokaler Distributor oder Joint Venture wegen Marktzugang und Regulierung\n• Positionierung: Premium-/Qualitäts-Image aus Deutschland gezielt nutzen"},
    # ---------- RISKS & OPPORTUNITIES (10) ----------
    {"prompt": "Welche Risiken und Chancen ergeben sich für einen mittelständischen Maschinenbauer, wenn er sein Geschäftsmodell von Einmalverkauf auf Subscription umstellt?",
     "ref": "• Risiken: Umsatzdelle im Übergang, Finanzierungsbedarf, Vertrieb muss umlernen, Kunden wollen Eigentum\n• Chancen: planbare wiederkehrende Umsätze, engere Kundenbindung, Nutzungsdaten für Service, höherer Lifetime-Value\n• Absicherung: Pilot mit einer Produktlinie, Hybrid-Angebot (Kauf + Abo), klare Kalkulation der Servicekosten"},
    {"prompt": "Welche Risiken und Chancen ergeben sich, wenn ein klassischer Reiseveranstalter voll auf Direktbuchung per App umstellt?",
     "ref": "• Risiken: Konflikt mit Reisebüros, Verlust älterer Kundengruppen, hohe App-/Marketingkosten, technischer Betrieb\n• Chancen: Margen ohne Vermittlerprovision, direkte Kundendaten, Personalisierung und Zusatzverkäufe\n• Absicherung: schrittweise Umstellung, Reisebüros als Service-Partner behalten, Zielgruppen-Test"},
    {"prompt": "Welche Risiken und Chancen entstehen, wenn ein deutscher Autohersteller seine Händler-Verträge kündigt und Direktvertrieb einführt?",
     "ref": "• Risiken: Rechtsstreit und Abfindungen, Verlust lokaler Präsenz und Service-Netz, Kundenirritation\n• Chancen: einheitliche Preise, volle Marge, direkte Kundenbeziehung und Daten, besseres Online-Erlebnis\n• Absicherung: Agenturmodell als Zwischenschritt, Händler als Service-Partner weiterführen"},
    {"prompt": "Welche Risiken und Chancen ergeben sich, wenn eine Drogeriekette ihre Eigenmarken stark ausbaut?",
     "ref": "• Risiken: Konflikt mit Markenherstellern (Konditionen, Auslistung), Qualitätsrisiko fällt auf die Kette zurück\n• Chancen: deutlich höhere Margen, Differenzierung, Preiseinstiegs-Segment besetzen, Kundenbindung\n• Absicherung: Kategorien mit schwacher Markenbindung zuerst, Qualitätssicherung, Zwei-Marken-Strategie"},
    {"prompt": "Welche Risiken und Chancen entstehen, wenn ein etablierter B2B-Software-Anbieter ein zusätzliches Selfservice-Angebot für kleinere Unternehmen startet?",
     "ref": "• Risiken: Kannibalisierung des Kerngeschäfts, Support-Aufwand durch viele Kleinkunden, Preisdruck nach unten\n• Chancen: neues Kundensegment, Funnel für spätere Upgrades, Skaleneffekte, Schutz gegen Billig-Wettbewerber\n• Absicherung: klare Produkt-/Feature-Trennung, separates Pricing, automatisierter Support"},
    {"prompt": "Welche Risiken und Chancen ergeben sich, wenn eine Bank ihren Filialbetrieb deutlich reduziert und auf rein digitale Kundenbetreuung umstellt?",
     "ref": "• Risiken: Verlust älterer/beratungsintensiver Kunden, Imageschaden in der Region, Beratungsqualität bei komplexen Produkten\n• Chancen: massive Kostensenkung, Investition in digitale Produkte, jüngere Zielgruppen\n• Absicherung: hybride Modelle (Video-Beratung, Partner-Standorte), Filialen datenbasiert statt pauschal schließen"},
    {"prompt": "Welche Risiken und Chancen entstehen, wenn ein Lebensmittel-Discounter seine Premium-Eigenmarken aggressiv ausweitet?",
     "ref": "• Risiken: Verwässerung des Preis-Images, Komplexität in Sortiment und Lieferkette, Kannibalisierung der Standard-Eigenmarken\n• Chancen: höhere Margen und Warenkörbe, neue Kundengruppen (Trading-down von Premium-Käufern), Differenzierung\n• Absicherung: klare Markenarchitektur, Tests in Pilotregionen, saisonale Premium-Aktionen zuerst"},
    {"prompt": "Welche Risiken und Chancen ergeben sich, wenn ein deutscher Mittelständler eine eigene Tochtergesellschaft in Polen aufbaut statt dort einen Distributor zu beauftragen?",
     "ref": "• Risiken: hohe Fixkosten und Anlaufverluste, fehlendes lokales Netzwerk, Rechts-/Personalthemen, längere Zeit bis zum Umsatz\n• Chancen: volle Marge und Kontrolle, direkte Kundenbeziehungen, Basis für weitere Osteuropa-Expansion\n• Absicherung: klein starten (Vertriebsbüro), lokales Management einstellen, Meilenstein-Plan mit Exit-Option"},
    {"prompt": "Welche Risiken und Chancen entstehen, wenn ein traditioneller Magazin-Verlag seine Print-Ausgabe einstellt und voll auf digitale Abos setzt?",
     "ref": "• Risiken: Verlust treuer Print-Leser und Anzeigenkunden, digitale Zahlungsbereitschaft unklar, Markenidentität\n• Chancen: Druck-/Vertriebskosten entfallen, Daten und Personalisierung, neue Formate (Podcast, Newsletter, Events)\n• Absicherung: Übergangsphase mit reduzierter Print-Frequenz, Print-Abonnenten aktiv migrieren, Paywall testen"},
    {"prompt": "Welche Risiken und Chancen ergeben sich, wenn eine Hotelkette ihr Loyalty-Programm an eine Airline-Allianz koppelt?",
     "ref": "• Risiken: Abhängigkeit vom Partner, geteilte Kundendaten, Programm-Kosten, eigene Marke tritt zurück\n• Chancen: Zugang zu Vielflieger-Kundschaft, höhere Auslastung durch Punkte-Einlösung, Differenzierung gegenüber unabhängigen Hotels\n• Absicherung: Pilot mit einer Region, klare Datenhoheit im Vertrag, Exklusivität vermeiden"},
    # ---------- FINANCIAL (10) ----------
    {"prompt": "Welche Hebel hat eine Fitnessstudio-Kette, um die Profitabilität pro Standort zu steigern?",
     "ref": "• Umsatz: Preisstaffeln und Premium-Mitgliedschaften, Personal Training und Kurse, Zusatzverkäufe (Getränke, Merch)\n• Auslastung: Off-Peak-Tarife, Firmenkooperationen, 24/7-Zugang\n• Kosten: Energie- und Flächenoptimierung, Personaleinsatz nach Stoßzeiten, Geräte-Leasing prüfen\n• Bindung: Kündigungsquote senken (Onboarding, Community) — billiger als Neugewinnung"},
    {"prompt": "Wie kann eine Online-Bekleidungs-Marke ihre Profitabilität erhöhen, ohne die Preise zu steigern?",
     "ref": "• Marge: Retouren senken (Größenberatung, bessere Fotos), Einkauf bündeln, Sortiment auf Renner fokussieren\n• Umsatz je Kunde: Bundles und Cross-Selling, Wiederkauf durch CRM/Newsletter, Treueprogramm\n• Kosten: Marketing-Mix auf effiziente Kanäle shiften, Fulfillment optimieren, Lagerumschlag erhöhen\n• Neue Quellen: Secondhand-/Outlet-Kanal für Restposten"},
    {"prompt": "Welche Hebel hat ein Bio-Supermarkt, um die Marge pro Filiale zu steigern?",
     "ref": "• Sortiment: margenstarke Eigenmarken, Frische-/Convenience-Anteil erhöhen, Regalplatz nach Marge steuern\n• Umsatz: Bon-Größe durch Platzierung und Aktionen, Kundenkarte, lokale Spezialitäten\n• Kosten: Abschriften/Food-Waste senken (dynamische Rabatte), Energieeffizienz, Personalplanung\n• Zusatz: Café-/Snack-Ecke, Catering und Gemüsekisten-Abo"},
    {"prompt": "Wie kann eine SaaS-Plattform für kleine Unternehmen ihren Customer-Lifetime-Value erhöhen?",
     "ref": "• Churn senken: besseres Onboarding, Health-Scores und proaktiver Support, Jahresverträge mit Anreiz\n• Expansion: Upselling in höhere Pläne, Zusatzmodule und Add-ons, nutzungsbasierte Komponenten\n• Preis: Pakete nach Wert staffeln, jährliche Preisanpassungen\n• Ökosystem: Integrationen und Partner-Apps erhöhen Wechselkosten"},
    {"prompt": "Welche Hebel hat eine Café-Kette, um die Profitabilität pro Standort zu steigern?",
     "ref": "• Umsatz: Frühstücks-/Lunch-Angebote, saisonale Specials, Bon-Größe durch Kombis und Gebäck\n• Auslastung: To-go und Pre-Order-App, tote Nachmittagszeiten mit Aktionen füllen, Abend-Nutzung (Events)\n• Kosten: Wareneinsatz standardisieren, Personal nach Frequenz planen, Schwund reduzieren\n• Extra: Bohnen/Merch-Verkauf, Catering, Treueprogramm"},
    {"prompt": "Wie kann ein Hersteller von Premium-Küchengeräten seine EBIT-Marge steigern?",
     "ref": "• Preis/Mix: Premium-Linien und limitierte Editionen, Preisdisziplin im Handel, Direktvertrieb ausbauen\n• Service: Ersatzteile, Garantieverlängerungen, Kochkurse/Content als Ökosystem\n• Kosten: Plattform-/Gleichteile-Strategie, Einkauf bündeln, Komplexität im Sortiment abbauen\n• Kanal: D2C-Onlineshop mit höherer Marge, Outlet für B-Ware statt Abschriften"},
    {"prompt": "Welche Hebel hat ein Wellness-Hotel, um die Profitabilität pro Gast zu erhöhen?",
     "ref": "• Umsatz je Gast: Treatments und Pakete vorab verkaufen, Upgrades (Zimmer, Late-Checkout), F&B-Angebote\n• Preis: dynamische Preise nach Saison/Auslastung, Längere-Aufenthalte-Anreize\n• Kosten: Energie (Pool/Sauna) optimieren, Personaleinsatz nach Belegung, Wareneinsatz Spa\n• Bindung: Direktbuchung statt OTA-Kommission, Gutscheine und Jahres-Specials"},
    {"prompt": "Wie kann ein deutscher Maschinenbauer im Mittelstand die Profitabilität seines Ersatzteil-Geschäfts steigern?",
     "ref": "• Preis: wertbasierte Ersatzteilpreise statt Kosten-plus, Express-Zuschläge, Bundles mit Service\n• Umsatz: Wartungsverträge und Teile-Abos, proaktive Ersatzempfehlungen (Sensorik), Nachrüst-Kits\n• Schutz: Originalteile-Argumentation gegen Drittanbieter, Seriennummern-Bindung\n• Kosten: Bestands- und Logistikoptimierung, 3D-Druck für Exoten"},
    {"prompt": "Welche Hebel hat ein Friseur-Salon-Franchise, um die Profitabilität pro Filiale zu erhöhen?",
     "ref": "• Umsatz: Zusatzleistungen (Färben, Pflege), Produktverkauf am Stuhl, Online-Terminbuchung gegen Leerlauf\n• Preis: Leistungsstaffeln (Junior/Senior-Stylist), Stoßzeiten-Preise\n• Auslastung: Randzeiten-Rabatte, Walk-in-Steuerung, No-Show-Gebühren\n• Kosten: Materialverbrauch standardisieren, Personalplanung nach Frequenz, Flächen teilen (Shop-in-Shop)"},
    {"prompt": "Wie kann eine deutsche Restaurant-Lieferplattform ihre Take-Rate-Profitabilität steigern?",
     "ref": "• Umsatz je Order: Mindestbestellwerte, Service-Gebühren differenzieren, Werbeplätze/Ads für Restaurants\n• Mix: Eigenzustellung nur wo dicht, sonst Restaurant-Zustellung, Abholung pushen\n• Zusatz: Abo-Modell (Liefer-Flat), White-Label-Logistik, Lebensmittel/Convenience als zweite Kategorie\n• Kosten: Fahrer-Routen bündeln, Betrugs-/Storno-Quote senken"},
]

HARD_CASES = [
    # ---------- MARKET ENTRY (10) ----------
    {"category": "market_entry",
     "prompt": "Ein deutscher Bierhersteller will in ein anderes europäisches Land expandieren. Nenne verschiedene Wege, wie er das tun kann — und sag kurz, welchen du zuerst testen würdest.",
     "ref": "• Export light: über lokale Getränke-Großhändler und Gastronomie-Distributoren listen\n• Handel: Listung bei Supermarkt-Ketten, zunächst als Spezialitäten-Import\n• Partner: Lizenz-/Braupartnerschaft mit lokaler Brauerei, Joint Venture\n• Eigenpräsenz: eigene Vertriebsgesellschaft, später lokale Braustätte; Brand-Bars/Taprooms als Marketing\n• Priorisierung: risikoarm mit Distributor + Gastronomie starten, bei Traktion eigene Strukturen"},
    {"category": "market_entry",
     "prompt": "Eine Bäckerei-Kette will ins Nachbarland expandieren, hat aber wenig Budget. Welche Optionen gibt es — und wie würdest du sie priorisieren?",
     "ref": "• Kapitalleicht: Franchise-Partner vor Ort, Lizenzmodell, Shop-in-Shop bei Supermärkten/Tankstellen\n• Test: 1-2 Pilotfilialen in Grenznähe, Food-Trucks/Marktstände als Markttest\n• Partner: Kooperation mit lokalem Bäcker (Co-Branding), Großhandel an Cafés/Hotels\n• Priorisierung: erst Pilot/Franchise (wenig Kapital, schnelles Lernen), Eigenfilialen später"},
    {"category": "market_entry",
     "prompt": "Ein reiner Online-Möbelhändler will erstmals stationär präsent sein. Welche Formate kommen infrage, und was spricht jeweils dafür oder dagegen?",
     "ref": "• Showroom (klein, zentral): Beratung + Bestellung online — geringe Fläche, kein Lager, aber keine Mitnahme\n• Flagship-Store: Markenerlebnis — teuer, nur in Top-Städten sinnvoll\n• Shop-in-Shop: Konzessionsfläche bei Möbelhäusern oder Kaufhäusern — schnell und günstig, wenig Kontrolle\n• Pop-up-Stores: Markttest je Stadt — flexibel, aber temporär\n• Outlet für Retouren/B-Ware: löst zugleich ein Kostenproblem"},
    {"category": "market_entry",
     "prompt": "Ein deutscher Streaming-Dienst für Dokumentationen will international wachsen. Wie kann er den Einstieg in neue Länder angehen?",
     "ref": "• Länderwahl: Sprachnähe (DACH, dann EN), Zahlungsbereitschaft, Wettbewerbsdichte\n• Leichtgewichtig: englische Version + Untertitel weltweit freischalten, Performance beobachten\n• Lokal: Untertitel/Dubbing, lokaler Content und Kuratierung, lokale Preise\n• Partner: Bundles mit Telkos/TV-Anbietern, Content-Lizenz-Deals mit lokalen Sendern\n• Marketing: Nischen-Communities (Wissenschaft, Natur) statt breiter Kampagnen"},
    {"category": "market_entry",
     "prompt": "Ein Hersteller von E-Scootern verkauft bisher nur an Privatkunden. Wie kann er zusätzlich ins Firmenkunden-Geschäft (B2B) einsteigen?",
     "ref": "• Segmente: Flotten für Lieferdienste, Mitarbeiter-Mobilität (Job-Scooter), Hotels/Campusse, Kommunen\n• Angebot: Leasing/Abo statt Kauf, Wartungs- und Serviceverträge, Flottenmanagement-Software\n• Vertrieb: eigenes Key-Account-Team, Partnerschaften mit Leasing-Firmen und Mobilitätsbudget-Anbietern\n• Start: Pilotkunden mit Referenzcharakter, dann Skalierung"},
    {"category": "market_entry",
     "prompt": "Eine Premium-Eismarke verkauft bisher nur über Supermärkte. Welche neuen Vertriebskanäle könnte sie erschließen — kurz- und langfristig?",
     "ref": "• Kurzfristig: Gastronomie (Restaurants, Cafés), Kioske und Tankstellen, Lieferdienste/Quick-Commerce\n• Erlebnis: eigene Eisdielen/Flagships, Food-Trucks, Events und Festivals\n• Direkt: Online-Versand (Trockeneis-Logistik), Abo-Boxen, Corporate Gifting\n• Langfristig: Travel Retail (Flughäfen), Export, Lizenzprodukte (Desserts, Shakes)"},
    {"category": "market_entry",
     "prompt": "Ein Anbieter einer Sprachlern-App für Privatnutzer will Unternehmen als Kunden gewinnen. Welche Einstiegswege gibt es?",
     "ref": "• Produkt: Team-Lizenzen mit Admin-Dashboard, Business-Sprachkurse (Meetings, E-Mails), Fortschritts-Reporting\n• Vertrieb: HR-/L&D-Abteilungen direkt, Benefits-Plattformen, HR-Software-Marktplätze\n• Einstieg: Freemium für Teams, Pilotprogramme mit Referenzkunden, Webinare\n• Partner: Weiterbildungsanbieter und Business Schools, Reseller"},
    {"category": "market_entry",
     "prompt": "Ein italienischer Modehändler will nach Deutschland expandieren — online, stationär oder beides? Nenne die Optionen und wäge kurz ab.",
     "ref": "• Online first: eigener DE-Shop + Zalando/About You — schnell, messbar, geringes Risiko; aber Marketingkosten und Retouren\n• Stationär: eigene Stores in Top-Lagen — Markenaufbau, aber teuer und langsam; Alternative: Shop-in-Shop/Konzession\n• Hybrid: online starten, Nachfrage-Städte identifizieren, dort Pop-ups → beste Lernkurve\n• Partner: Wholesale an Multibrand-Boutiquen als risikoarmer Türöffner"},
    {"category": "market_entry",
     "prompt": "Ein Betreiber von Padel-Tennis-Hallen will in zwei Jahren von 3 auf 20 Standorte wachsen. Welche Wege gibt es, so schnell zu skalieren?",
     "ref": "• Kapital: Investoren/Private Equity, Sale-and-Leaseback der Immobilien, Fremdkapital\n• Modelle: Franchise, Joint Ventures mit lokalen Betreibern, Management-Verträge für fremde Hallen\n• Anorganisch: Übernahme bestehender Padel-/Tennis-Anlagen und Umbau\n• Leicht: Flächen mieten statt bauen (Hallen, Industrieflächen), Partnerschaften mit Fitnessketten"},
    {"category": "market_entry",
     "prompt": "Ein deutscher Tiefkühlkost-Hersteller beliefert bisher nur den Einzelhandel. Wie kann er in die Gastronomie (B2B) einsteigen, und worauf sollte er achten?",
     "ref": "• Zugang: Gastro-Großhändler (Metro, Transgourmet) listen, eigener Außendienst für Ketten, Messen\n• Angebot: Großgebinde und Convenience-Grade, Speisekarten-Lösungen, verlässliche Liefer-Logistik\n• Segmente: Systemgastronomie, Kantinen/Caterer, Hotels — unterschiedliche Anforderungen\n• Achtung: andere Margen- und Preislogik, Kannibalisierung vermeiden, ggf. eigene B2B-Marke"},
    # ---------- RISKS & OPPORTUNITIES (10) ----------
    {"category": "risks_opportunities",
     "prompt": "Eine Supermarktkette überlegt, nachts unbemannte, kassenlose Mini-Filialen anzubieten. Welche Risiken und Chancen siehst du?",
     "ref": "• Chancen: Umsatz in toten Stunden, Differenzierung, Personalkosten minimal, Daten über Nachtnachfrage\n• Risiken: Diebstahl/Vandalismus, Technikkosten und -ausfälle, Akzeptanz älterer Kunden, rechtliche Fragen\n• Absicherung: Pilot an 2-3 Standorten, Kameratechnik + App-Zugang, begrenztes Sortiment"},
    {"category": "risks_opportunities",
     "prompt": "Ein Spielzeughersteller will KI-gestützte, sprechende Kuscheltiere auf den Markt bringen. Welche Risiken und Chancen siehst du?",
     "ref": "• Chancen: Differenzierung und Premium-Preis, wiederkehrende Umsätze (Abo/Inhalte), starkes Medieninteresse\n• Risiken: Datenschutz bei Kindern (sehr sensibel!), Fehlverhalten der KI, Batterien/Sicherheit, Eltern-Skepsis\n• Absicherung: Offline-Modus und strenge Inhaltsfilter, Zertifizierungen, transparente Eltern-Kontrolle"},
    {"category": "risks_opportunities",
     "prompt": "Eine Airline überlegt, für Handgepäck eine Gebühr einzuführen. Welche Risiken und Chancen siehst du?",
     "ref": "• Chancen: Zusatzerlöse, schnelleres Boarding, wettbewerbsfähigere Basispreise in Vergleichsportalen\n• Risiken: Imageschaden und Kundenabwanderung, schlechte Presse, Vergleichbarkeit sinkt scheinbar — Vertrauensverlust\n• Absicherung: nur bei Basistarifen, klare Kommunikation, Vielflieger ausnehmen, A/B-Test auf ausgewählten Strecken"},
    {"category": "risks_opportunities",
     "prompt": "Eine Traditionsbrauerei will ein alkoholfreies Trend-Getränk für die Gen Z launchen. Welche Risiken und Chancen siehst du?",
     "ref": "• Chancen: Wachstumsmarkt alkoholfrei, neue junge Zielgruppe, Nutzung vorhandener Brau- und Vertriebs-Infrastruktur\n• Risiken: Marke passt nicht zur Zielgruppe (zu traditionell), Kannibalisierung des Kerngeschäfts, Trend-Lebensdauer\n• Absicherung: eigenständige Marke statt Dachmarke, Social-Media-first-Marketing, limitierter Test-Launch"},
    {"category": "risks_opportunities",
     "prompt": "Ein Möbelhaus will Möbel im Abo vermieten statt nur zu verkaufen. Welche Risiken und Chancen siehst du?",
     "ref": "• Chancen: wiederkehrende Umsätze, junge/mobile Zielgruppen (Studenten, Expats), B2B (Büros, möblierte Wohnungen)\n• Risiken: Kapitalbindung im Bestand, Abnutzung und Aufbereitungskosten, Logistik, Kannibalisierung des Verkaufs\n• Absicherung: robustes Sortiment für Miete, B2B zuerst, Preis so kalkulieren, dass 2. und 3. Mietzyklus profitabel sind"},
    {"category": "risks_opportunities",
     "prompt": "Eine Krankenkasse will Fitness-Tracker-Daten für Beitrags-Boni nutzen. Welche Risiken und Chancen siehst du?",
     "ref": "• Chancen: gesündere Versicherte und geringere Kosten, Differenzierung, junge Zielgruppen, Präventions-Image\n• Risiken: Datenschutz und öffentliche Debatte, Diskriminierungsvorwurf (Benachteiligung Kranker), Manipulation der Daten\n• Absicherung: freiwillig und bonus-basiert (nie Malus), Datensparsamkeit, unabhängige Zertifizierung"},
    {"category": "risks_opportunities",
     "prompt": "Ein Modehändler will einen großen Secondhand-Bereich in seinen Filialen einführen. Welche Risiken und Chancen siehst du?",
     "ref": "• Chancen: Nachhaltigkeits-Image, neue preisbewusste Kunden, Frequenz durch Ankauf, Marge auf kuratierte Ware\n• Risiken: Kannibalisierung des Neuware-Geschäfts, aufwändige Prozesse (Prüfung, Aufbereitung), Flächenverlust\n• Absicherung: Pilotfilialen, klare Flächen-Trennung, Ankauf gegen Gutscheine (bindet Umsatz im Haus)"},
    {"category": "risks_opportunities",
     "prompt": "Ein Stadtwerk will große E-Auto-Ladeparks in der Innenstadt bauen. Welche Risiken und Chancen siehst du?",
     "ref": "• Chancen: Wachstumsmarkt, Standortvorteil und Netz-Know-how, Zusatzgeschäft (Shop, Werbung), kommunale Unterstützung\n• Risiken: hohe Investitionen bei unsicherer Auslastung, Technologie-/Preisrisiko Strom, private Wettbewerber (Tesla, EnBW)\n• Absicherung: stufenweiser Ausbau, Anker-Partner (Taxi-/Carsharing-Flotten), Kombination mit Parkhäusern"},
    {"category": "risks_opportunities",
     "prompt": "Eine Fast-Food-Kette will Filialen mit vollautomatischer Küche und ohne Personal testen. Welche Risiken und Chancen siehst du?",
     "ref": "• Chancen: Personalkosten und -mangel gelöst, 24/7-Betrieb, konstante Qualität, PR-Effekt\n• Risiken: hohe Technikkosten und Ausfälle, Kundenerlebnis leidet, öffentliche Jobverlust-Debatte, begrenztes Menü\n• Absicherung: Hybrid (Automatisierung hinten, Mensch vorn), Standorte mit hohem Durchsatz zuerst, Wartungsverträge"},
    {"category": "risks_opportunities",
     "prompt": "Ein Schulbuch-Verlag will neue Bücher nur noch digital anbieten. Welche Risiken und Chancen siehst du?",
     "ref": "• Chancen: keine Druck-/Lagerkosten, Updates und interaktive Inhalte, Lizenzmodelle je Schüler, Lernanalysen\n• Risiken: Schul-Infrastruktur und Bundesland-Vorgaben, Lehrer-Akzeptanz, Piraterie, Verlust des Gebrauchtmarkt-Ersatzkaufs\n• Absicherung: hybride Übergangsphase, Pilotschulen, Bundle Print+Digital, starke Lehrerfortbildung"},
    # ---------- FINANCIAL (10) ----------
    {"category": "financial",
     "prompt": "Ein Kino ist unter der Woche halb leer. Welche Ideen hast du, Umsatz und Profitabilität zu steigern — ohne einfach die Ticketpreise zu erhöhen?",
     "ref": "• Auslastung: Themen-Abende (Horror-Dienstag), Senioren-/Studenten-Nachmittage, Abo-Modell (Kino-Flat)\n• Neue Nutzung: Säle tagsüber vermieten (Firmen-Events, Gaming-Turniere, Vorlesungen), Kindergeburtstage\n• Umsatz je Besucher: Food-&-Beverage-Bundles, Premium-Sitze, Vorbestellung per App\n• Partnerschaften: Restaurants (Dinner+Kino), lokale Vereine, Sneak-Previews"},
    {"category": "financial",
     "prompt": "Ein Freizeitpark will den Umsatz pro Besucher steigern. Sammle Ideen entlang des gesamten Besuchs — von der Buchung bis zum Verlassen des Parks.",
     "ref": "• Vor dem Besuch: Online-Upsells (Express-Pass, Parken, Menü-Deals), dynamische Ticketpreise, Übernachtungs-Pakete\n• Im Park: Fotos und Videos der Fahrten, Merchandising an Attraktionen, Premium-Erlebnisse (VIP-Tour, Fast Lane)\n• Essen: Themen-Restaurants, Refill-Becher, Family-Bundles\n• Danach: Jahreskarten-Upgrade am Ausgang, Online-Shop, Geburtstags-/Event-Angebote"},
    {"category": "financial",
     "prompt": "Eine Autowerkstatt-Kette will profitabler werden. Welche Hebel gibt es auf der Umsatz- und auf der Kostenseite?",
     "ref": "• Umsatz: Wartungspakete und Service-Abos, Zusatzverkäufe (Reifen, Wischer) am Termin, Hol-/Bring-Service gegen Gebühr\n• Preis: transparente Paketpreise statt Stundensätze, Express-Zuschläge\n• Kosten: Teile-Einkauf bündeln, Werkstattauslastung glätten (Online-Termine), Standardzeiten je Reparatur\n• Bindung: Erinnerungs-Service (TÜV, Inspektion), Flottenverträge mit Firmen"},
    {"category": "financial",
     "prompt": "Ein Zoo sucht neue, wiederkehrende Einnahmequellen. Welche Ideen hast du?",
     "ref": "• Mitgliedschaften: Jahreskarten-Stufen, Familien-Abos, Förderkreis\n• Patenschaften: Tier-Patenschaften für Privatpersonen und Firmen\n• Events: Abendführungen, Übernachtungen im Zoo, Firmenevents und Hochzeiten\n• B2B/Content: Bildungsprogramme für Schulen im Abo, Kamera-Livestreams mit Sponsoring, Gastro-/Shop-Verpachtung"},
    {"category": "financial",
     "prompt": "Ein Buchverlag will seine Marge verbessern, ohne mehr Bücher verkaufen zu müssen. Welche Möglichkeiten siehst du?",
     "ref": "• Direkt: eigener Online-Shop und Direktvertrieb (Handelsrabatt spart 40-50 %), signierte Sonderausgaben\n• Formate: E-Book/Hörbuch (kein Druck), Print-on-Demand für Backlist statt Lager\n• Rechte: Lizenzen (Übersetzung, Film, Hörspiel), Bundles\n• Kosten: Druck bündeln, Remittenden senken (kleinere Erstauflagen), Backlist pflegen statt Novitäten-Flut"},
    {"category": "financial",
     "prompt": "Eine Bowlingbahn ist abends voll, tagsüber leer. Welche Möglichkeiten gibt es, die leeren Stunden zu Geld zu machen?",
     "ref": "• Zielgruppen tagsüber: Senioren-Ligen, Schulen und Kindergärten, Schichtarbeiter, Studenten-Deals\n• B2B: Firmen-Teamevents, Meetingraum + Bowling-Pakete\n• Fläche anders nutzen: Co-Working mit Kaffee, Kurse/Events, Kindergeburtstage am Nachmittag\n• Preis: dynamische Preise (Happy Hour), Tages-Flatrates, Abo-Modelle"},
    {"category": "financial",
     "prompt": "Ein Software-Anbieter hat nur einen einzigen Abo-Preis für alle Kunden. Wie könnte er seine Monetarisierung weiterentwickeln?",
     "ref": "• Stufen: Basic/Pro/Enterprise nach Funktionsumfang, Team-Preise pro Nutzer\n• Nutzung: nutzungsbasierte Komponenten (API-Calls, Speicher), Add-ons und Module\n• Segmente: günstiger Einstieg für Kleine, Enterprise mit Support-SLA und Security-Features\n• Extras: Jahreszahlung mit Rabatt, Onboarding-/Schulungspakete, Partner-Marktplatz mit Umsatzbeteiligung"},
    {"category": "financial",
     "prompt": "Ein Fußballverein aus der 2. Liga will seine Einnahmen diversifizieren. Sammle Ideen — von naheliegend bis kreativ.",
     "ref": "• Stadion: Events und Konzerte, Stadiontouren, Business-Seats und Logen unter der Woche vermieten\n• Fans: Mitglieder-Abos mit Content, eSports-Team, Fan-Token/Kollektionen, internationaler Merch-Shop\n• Partner: Namensrechte (Stadion, Trainingszentrum), regionale Business-Netzwerke\n• Entwicklung: Nachwuchsleistungszentrum + Transfererlöse, Fußballschulen und Camps, Immobilien am Stadion"},
    {"category": "financial",
     "prompt": "Eine Bäckerei wirft jeden Abend viel unverkaufte Ware weg. Welche Ideen hast du, daraus Umsatz zu machen oder Kosten zu sparen?",
     "ref": "• Abverkauf: Abend-Rabatte (ab 17 Uhr −50 %), Überraschungstüten (Too Good To Go), Vortagsware-Ecke\n• Weiterverwertung: Croutons/Semmelbrösel/Chips aus Brot, Brotpudding und Snacks, Tierfutter-Kooperationen\n• Steuerung: bessere Produktionsplanung nach Wochentag/Wetter, Sortiment am Abend ausdünnen, Vorbestellungen\n• Sozial/Marke: Spenden an Tafeln (Entsorgungskosten sparen + Image)"},
    {"category": "financial",
     "prompt": "Ein Co-Working-Anbieter will die Profitabilität je Standort erhöhen. Welche Hebel siehst du auf Umsatz- und Kostenseite?",
     "ref": "• Umsatz: Meetingräume stundenweise an Externe, virtuelle Büro-Adressen, Events/Workshops, Kaffee-/Snack-Upsells\n• Mix: feste Büros (höhere Marge) vs. Flex-Desks ausbalancieren, Team-Pakete, Enterprise-Kunden\n• Auslastung: Tages-/Abendpässe, Wochenend-Nutzung (Kurse, Communities)\n• Kosten: Flächen untervermieten, Energie smart steuern, Reinigung/Services poolen"},
]
